# Generated by Django 5.2 on 2025-04-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MTTB_Divisions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Div_Id", models.CharField(max_length=20, unique=True)),
                ("Div_NameL", models.CharField(blank=True, max_length=250, null=True)),
                ("Div_NameE", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "verbose_name_plural": "DivisionInfo",
            },
        ),
        migrations.CreateModel(
            name="MTTB_Function_Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Function_Id", models.CharField(max_length=15, unique=True)),
                (
                    "Function_Desc",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("Main_Menu", models.CharField(blank=True, max_length=250)),
                ("Sub_Menu", models.CharField(blank=True, max_length=250)),
                ("All_Link", models.CharField(blank=True, max_length=500)),
                ("Function_Status", models.CharField(blank=True, max_length=1)),
            ],
            options={
                "verbose_name_plural": "Function_Description",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MTTB_Role_Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Role_Id", models.CharField(max_length=20, unique=True)),
                ("Role_NameL", models.CharField(blank=True, max_length=250, null=True)),
                ("Role_NameE", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "verbose_name_plural": "Role_MasterInfo",
            },
        ),
        migrations.CreateModel(
            name="STTB_Dates",
            fields=[
                ("DateID", models.AutoField(primary_key=True, serialize=False)),
                ("InsertToday", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "Prev_Wroking_Day",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "Next_working_Day",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("eod_time", models.CharField(max_length=1)),
            ],
            options={
                "verbose_name_plural": "EndOfDateInfo",
                "ordering": ["DateID"],
            },
        ),
        migrations.CreateModel(
            name="STTB_MDdulesInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("M_Id", models.CharField(max_length=50)),
                ("M_NameL", models.CharField(max_length=250)),
                ("M_NameE", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "MDdulesInfo",
            },
        ),
        migrations.CreateModel(
            name="MTTB_Role_Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("New_Detail", models.IntegerField(default=0)),
                ("Del_Detail", models.IntegerField(default=0)),
                ("Edit_Detail", models.IntegerField(default=0)),
                ("Auth_Detail", models.IntegerField(default=0)),
                (
                    "Function_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_function_description",
                    ),
                ),
                (
                    "Role_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_role_master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Role_Detail",
            },
        ),
        migrations.CreateModel(
            name="MTTB_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_Id", models.CharField(max_length=10, unique=True)),
                ("User_Name", models.CharField(max_length=250)),
                ("User_Password", models.CharField(max_length=250)),
                ("User_Email", models.CharField(blank=True, max_length=250, null=True)),
                ("User_Mobile", models.CharField(blank=True, max_length=15, null=True)),
                ("User_Status", models.BooleanField(default=True)),
                ("InsertDate", models.DateTimeField(auto_now_add=True)),
                ("UpdateDate", models.DateTimeField(auto_now=True)),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_users",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
                (
                    "Div_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_divisions",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_users",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
                (
                    "Role_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_role_master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "UsersRgith",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="mttb_role_master",
            name="Checker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checked_roles",
                to="SAMCSYS.mttb_user",
            ),
        ),
        migrations.AddField(
            model_name="mttb_role_master",
            name="Maker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_roles",
                to="SAMCSYS.mttb_user",
            ),
        ),
        migrations.AddField(
            model_name="mttb_divisions",
            name="Checker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checked_divisions",
                to="SAMCSYS.mttb_user",
            ),
        ),
        migrations.AddField(
            model_name="mttb_divisions",
            name="Maker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_divisions",
                to="SAMCSYS.mttb_user",
            ),
        ),
        migrations.CreateModel(
            name="STTB_Current_Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Host_UserLogin", models.CharField(max_length=255)),
                ("Start_time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "User_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Current_UserInfo",
            },
        ),
        migrations.AddField(
            model_name="mttb_function_description",
            name="M_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SAMCSYS.sttb_mddulesinfo",
            ),
        ),
    ]
