# Generated by Django 5.2 on 2025-05-04 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAMCSYS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MTTB_Ccy_DEFN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ccy_Code", models.CharField(max_length=20, unique=True)),
                ("Ccy_NameL", models.CharField(blank=True, max_length=250, null=True)),
                ("Country", models.CharField(blank=True, max_length=20, null=True)),
                ("Ccy_Decimals", models.IntegerField(default=0)),
                ("ALT_Ccy_Code", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_Ccy_DEFN",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_Ccy_DEFN",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Currency_DEFN_Info",
            },
        ),
    ]
