# Generated by Django 5.2 on 2025-05-04 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAMCSYS", "0006_mttb_lcl_holiday"),
    ]

    operations = [
        migrations.CreateModel(
            name="MTTB_GLMaster",
            fields=[
                ("glid", models.AutoField(primary_key=True, serialize=False)),
                ("gl_code", models.CharField(blank=True, max_length=10, null=True)),
                ("gl_Desc", models.CharField(blank=True, max_length=250, null=True)),
                ("glTpe", models.CharField(blank=True, max_length=1, null=True)),
                ("category", models.CharField(blank=True, max_length=1, null=True)),
                ("retal", models.CharField(blank=True, max_length=1, null=True)),
                ("ccy_Res", models.CharField(blank=True, max_length=1, null=True)),
                ("Res_ccy", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Allow_BackPeriodEntry",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "pl_Split_ReqD",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_GLMaster",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_GLMaster",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GLMaster",
            },
        ),
        migrations.CreateModel(
            name="MTTB_GLSub",
            fields=[
                ("glid", models.AutoField(primary_key=True, serialize=False)),
                ("glsub", models.CharField(blank=True, max_length=20, null=True)),
                ("glsub_Desc", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_GL_sub",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_GL_sub",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
                (
                    "gl_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_glmaster",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GLSub",
            },
        ),
    ]
