# Generated by Django 5.2 on 2025-05-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAMCSYS", "0007_mttb_glmaster_mttb_glsub"),
    ]

    operations = [
        migrations.CreateModel(
            name="MTTB_Fin_Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fin_cycle", models.CharField(max_length=10, unique=True)),
                ("cycle_Desc", models.CharField(blank=True, max_length=250, null=True)),
                ("StartDate", models.DateTimeField(blank=True, null=True)),
                ("EndDate", models.DateTimeField(blank=True, null=True)),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_Fin_Cycle",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_Fin_Cycle",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FinCycle",
            },
        ),
    ]
