# Generated by Django 5.2 on 2025-05-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAMCSYS", "0008_mttb_fin_cycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="MTTB_Per_Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_code", models.CharField(max_length=20, unique=True)),
                ("PC_StartDate", models.DateTimeField(blank=True, null=True)),
                ("PC_EndDate", models.DateTimeField(blank=True, null=True)),
                (
                    "Fin_cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_fin_cycle",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PerCode",
            },
        ),
    ]
