# Generated by Django 5.2 on 2025-05-04 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAMCSYS", "0009_mttb_per_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="MTTB_DATA_Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "JRN_REKEY_REQUIRED",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "JRN_REKEY_VALUE_DATE",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "JRN_REKEY_AMOUNT",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "JRN_REKEY_TXN_CODE",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("BACK_VALUE", models.CharField(blank=True, max_length=1, null=True)),
                ("MOD_NO", models.IntegerField(blank=True, max_length=1, null=True)),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_DATA_Entry",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_DATA_Entry",
                        to="SAMCSYS.mttb_user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DATA_Entry",
            },
        ),
    ]
