# Generated by Django 5.2 on 2025-05-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAMCSYS", "0010_mttb_data_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mttb_data_entry",
            name="BACK_VALUE",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="mttb_data_entry",
            name="MOD_NO",
            field=models.IntegerField(default=0),
        ),
    ]
