# Generated by Django 5.0.14 on 2025-05-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0011_alter_mttb_data_entry_back_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_user',
            name='Auth_Status',
            field=models.CharField(choices=[('A', 'Approved'), ('U', 'Unapproved')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='mttb_user',
            name='Once_Auth',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='mttb_user',
            name='User_Status',
            field=models.CharField(choices=[('E', 'Enabled'), ('D', 'Disabled')], default='E', max_length=1),
        ),
    ]
