# Generated by Django 5.0.14 on 2025-05-12 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0012_alter_mttb_user_auth_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTTB_MAIN_MENU',
            fields=[
                ('menu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('menu_name_la', models.CharField(blank=True, max_length=250, null=True)),
                ('menu_name_en', models.CharField(blank=True, max_length=250, null=True)),
                ('menu_icon', models.CharField(blank=True, max_length=250, null=True)),
                ('menu_order', models.CharField(blank=True, max_length=3, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'MAIN_MENU',
            },
        ),
        migrations.CreateModel(
            name='STTB_ModulesInfo',
            fields=[
                ('module_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('module_name_la', models.CharField(max_length=250)),
                ('module_name_en', models.CharField(max_length=250)),
                ('module_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('module_order', models.CharField(blank=True, max_length=3, null=True)),
                ('is_active', models.CharField(max_length=1)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=30, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ModulesInfo',
            },
        ),
        migrations.RemoveField(
            model_name='mttb_function_description',
            name='M_Id',
        ),
        migrations.RemoveField(
            model_name='mttb_role_detail',
            name='Function_Id',
        ),
        migrations.RemoveField(
            model_name='mttb_user',
            name='Checker_Id',
        ),
        migrations.RemoveField(
            model_name='mttb_user',
            name='Div_Id',
        ),
        migrations.RemoveField(
            model_name='mttb_user',
            name='Maker_Id',
        ),
        migrations.RemoveField(
            model_name='mttb_user',
            name='Role_ID',
        ),
        migrations.RemoveField(
            model_name='sttb_current_users',
            name='User_Id',
        ),
        migrations.AlterModelOptions(
            name='mttb_data_entry',
            options={'verbose_name_plural': 'DaTa_Entry'},
        ),
        migrations.AlterModelOptions(
            name='mttb_divisions',
            options={'verbose_name_plural': 'DivisionsInfo'},
        ),
        migrations.AlterModelOptions(
            name='sttb_dates',
            options={'ordering': ['date_id'], 'verbose_name_plural': 'EndOfDateInfo'},
        ),
        migrations.RenameField(
            model_name='mttb_ccy_defn',
            old_name='Ccy_NameL',
            new_name='Ccy_Name_en',
        ),
        migrations.RenameField(
            model_name='mttb_divisions',
            old_name='Div_NameE',
            new_name='division_name_en',
        ),
        migrations.RenameField(
            model_name='mttb_divisions',
            old_name='Div_NameL',
            new_name='division_name_la',
        ),
        migrations.RenameField(
            model_name='mttb_divisions',
            old_name='Record_Status',
            new_name='record_Status',
        ),
        migrations.RenameField(
            model_name='mttb_exc_rate',
            old_name='CCy_Code',
            new_name='ccy_code',
        ),
        migrations.RenameField(
            model_name='mttb_exc_rate_history',
            old_name='CCy_Code',
            new_name='ccy_code',
        ),
        migrations.RenameField(
            model_name='mttb_glmaster',
            old_name='glTpe',
            new_name='glType',
        ),
        migrations.RenameField(
            model_name='mttb_glmaster',
            old_name='gl_Desc',
            new_name='gl_Desc_en',
        ),
        migrations.RenameField(
            model_name='mttb_glsub',
            old_name='glsub_Desc',
            new_name='glsub_Desc_en',
        ),
        migrations.RenameField(
            model_name='mttb_glsub',
            old_name='glsub',
            new_name='glsub_code',
        ),
        migrations.RenameField(
            model_name='mttb_glsub',
            old_name='glid',
            new_name='glsub_id',
        ),
        migrations.RenameField(
            model_name='mttb_role_master',
            old_name='Record_Status',
            new_name='record_Status',
        ),
        migrations.RenameField(
            model_name='mttb_role_master',
            old_name='Role_NameE',
            new_name='role_name_en',
        ),
        migrations.RenameField(
            model_name='mttb_role_master',
            old_name='Role_NameL',
            new_name='role_name_la',
        ),
        migrations.RenameField(
            model_name='sttb_dates',
            old_name='DateID',
            new_name='date_id',
        ),
        migrations.RenameField(
            model_name='sttb_dates',
            old_name='InsertToday',
            new_name='insertToday',
        ),
        migrations.RenameField(
            model_name='sttb_dates',
            old_name='Next_working_Day',
            new_name='next_working_Day',
        ),
        migrations.RenameField(
            model_name='sttb_dates',
            old_name='Prev_Wroking_Day',
            new_name='prev_Wroking_Day',
        ),
        migrations.RemoveField(
            model_name='mttb_ccy_defn',
            name='Ccy_Code',
        ),
        migrations.RemoveField(
            model_name='mttb_ccy_defn',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mttb_data_entry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mttb_divisions',
            name='Div_Id',
        ),
        migrations.RemoveField(
            model_name='mttb_divisions',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mttb_fin_cycle',
            name='Fin_cycle',
        ),
        migrations.RemoveField(
            model_name='mttb_fin_cycle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mttb_lcl_holiday',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mttb_per_code',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mttb_role_detail',
            name='Role_Id',
        ),
        migrations.RemoveField(
            model_name='mttb_role_master',
            name='Role_Id',
        ),
        migrations.RemoveField(
            model_name='mttb_role_master',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mttb_trn_code',
            name='Trn_Desc',
        ),
        migrations.RemoveField(
            model_name='mttb_trn_code',
            name='Trn_code',
        ),
        migrations.RemoveField(
            model_name='mttb_trn_code',
            name='id',
        ),
        migrations.AddField(
            model_name='mttb_ccy_defn',
            name='Ccy_Name_la',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mttb_data_entry',
            name='data_entry_id',
            field=models.CharField(default=2, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mttb_glmaster',
            name='gl_Desc_la',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mttb_glsub',
            name='glsub_Desc_la',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mttb_lcl_holiday',
            name='lcl_holiday_id',
            field=models.CharField(default=5, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mttb_trn_code',
            name='trn_Desc_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mttb_trn_code',
            name='trn_Desc_la',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_ccy_defn',
            name='Ccy_Decimals',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate',
            name='Buy_Rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate',
            name='Sale_Rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate_history',
            name='Buy_Rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate_history',
            name='Sale_Rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mttb_glmaster',
            name='gl_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_per_code',
            name='period_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MTTB_SUB_MENU',
            fields=[
                ('sub_menu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_menu_name_la', models.CharField(max_length=250)),
                ('sub_menu_name_en', models.CharField(max_length=250)),
                ('sub_menu_icon', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_menu_order', models.CharField(blank=True, max_length=3, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('menu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_main_menu')),
            ],
            options={
                'verbose_name_plural': 'SUB_MENU',
            },
        ),
        migrations.CreateModel(
            name='MTTB_Function_Desc',
            fields=[
                ('function_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Function_Id')),
                ('description_la', models.CharField(max_length=200)),
                ('description_en', models.CharField(blank=True, max_length=200, null=True)),
                ('all_link', models.CharField(blank=True, max_length=200, null=True)),
                ('eod_function', models.CharField(blank=True, max_length=1, null=True)),
                ('function_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=30, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('sub_menu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_sub_menu')),
            ],
            options={
                'verbose_name_plural': 'Function_Description',
                'ordering': ['function_id'],
            },
        ),
        migrations.CreateModel(
            name='MTTB_Users',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=250)),
                ('user_password', models.CharField(max_length=250)),
                ('user_email', models.CharField(blank=True, max_length=250, null=True)),
                ('user_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('User_Status', models.BooleanField(default=True)),
                ('pwd_changed_on', models.DateField(blank=True, null=True)),
                ('InsertDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Auth_Status', models.CharField(blank=True, max_length=1, null=True)),
                ('Once_Auth', models.CharField(blank=True, max_length=1, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_userss', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_userss', to='SAMCSYS.mttb_users')),
                ('Role_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_role_master')),
                ('div_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_divisions')),
            ],
            options={
                'verbose_name_plural': 'UsersRgith',
            },
        ),
        migrations.AlterField(
            model_name='mttb_ccy_defn',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_Ccy_DEFN', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_ccy_defn',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_Ccy_DEFN', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_data_entry',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_DATA_Entry', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_data_entry',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_DATA_Entry', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_divisions',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_division', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_divisions',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_division', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_Exc_Rate', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_Exc_Rate', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate_history',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_Exc_Rate_History', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate_history',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_Exc_RateHistory', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_fin_cycle',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_Fin_Cycle', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_fin_cycle',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_Fin_Cycle', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_glmaster',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_GLMaster', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_glmaster',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_GLMaster', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_glsub',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_GL_sub', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_glsub',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_GL_sub', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_lcl_holiday',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_TLCL_Holiday', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_lcl_holiday',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_TLCL_Holiday', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_role_master',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_roles', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_role_master',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_roles', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_trn_code',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_Trn_Code', to='SAMCSYS.mttb_users'),
        ),
        migrations.AlterField(
            model_name='mttb_trn_code',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_Trn_Code', to='SAMCSYS.mttb_users'),
        ),
        migrations.AddField(
            model_name='mttb_main_menu',
            name='module_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.sttb_modulesinfo', verbose_name='module_Id'),
        ),
        migrations.DeleteModel(
            name='STTB_MDdulesInfo',
        ),
        migrations.DeleteModel(
            name='MTTB_Function_Description',
        ),
        migrations.AddField(
            model_name='mttb_role_detail',
            name='function_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_function_desc'),
        ),
        migrations.AddField(
            model_name='sttb_current_users',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_users'),
        ),
        migrations.AddField(
            model_name='mttb_ccy_defn',
            name='ccy_code',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mttb_divisions',
            name='div_id',
            field=models.CharField(default=3, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mttb_fin_cycle',
            name='fin_cycle',
            field=models.CharField(default=4, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mttb_role_detail',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_role_master'),
        ),
        migrations.AddField(
            model_name='mttb_role_master',
            name='role_id',
            field=models.CharField(default=6, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mttb_trn_code',
            name='trn_code',
            field=models.CharField(default=7, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MTTB_User',
        ),
    ]
