# Generated by Django 5.0.14 on 2025-05-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0012_sttb_gl_bal'),
    ]

    operations = [
        migrations.CreateModel(
            name='STTB_GL_SUB_BAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.CharField(blank=True, max_length=9, null=True)),
                ('dr_mov', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('cr_mov', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('dr_mov_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('cr_mov_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('dr_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('cr_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('dr_bal_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('cr_bal_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('open_dr_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('open_cr_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('open_dr_bal_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('open_cr_bal_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('CCy_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_ccy_defn')),
                ('gl_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_glmaster')),
                ('period_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_per_code')),
            ],
            options={
                'verbose_name_plural': 'GL_SUB_BAL',
            },
        ),
    ]
