# Generated by Django 5.0.14 on 2025-05-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0013_mttb_main_menu_sttb_modulesinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_users',
            name='User_Status',
            field=models.CharField(choices=[('E', 'Enabled'), ('D', 'Disabled')], default='E', max_length=1),
        ),
    ]
