# Generated by Django 5.0.14 on 2025-05-10 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0014_actb_dairy_log_actb_dairy_log_history_mttb_main_menu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mttb_function_description',
            options={'ordering': ['Function_Id'], 'verbose_name_plural': 'Function_Description'},
        ),
        migrations.RemoveField(
            model_name='mttb_function_description',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mttb_function_description',
            name='module',
        ),
        migrations.RemoveField(
            model_name='sttb_mddulesinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='sttb_mddulesinfo',
            name='is_active',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sttb_mddulesinfo',
            name='module_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sttb_mddulesinfo',
            name='module_id',
            field=models.CharField(default=2, max_length=2, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sttb_mddulesinfo',
            name='module_order',
            field=models.CharField(default=2, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mttb_function_description',
            name='Function_Id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mttb_function_description',
            name='sub_menu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_sub_menu'),
        ),
        migrations.AlterField(
            model_name='mttb_main_menu',
            name='menu_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mttb_sub_menu',
            name='menu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_main_menu'),
        ),
    ]
