# Generated by Django 5.0.14 on 2025-05-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0015_detb_jrnl_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETB_JRNL_LOG_HIST',
            fields=[
                ('Reference_No', models.AutoField(primary_key=True, serialize=False)),
                ('Ccy_cd', models.CharField(max_length=3)),
                ('Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('Lcy_Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('Dr_cr', models.CharField(max_length=1)),
                ('Account', models.CharField(max_length=20)),
                ('Txn_code', models.CharField(blank=True, max_length=3, null=True)),
                ('Value_date', models.DateTimeField(blank=True, null=True)),
                ('Exch_rate', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('fin_cycle', models.CharField(blank=True, max_length=9, null=True)),
                ('Period_code', models.CharField(blank=True, max_length=3, null=True)),
                ('Addl_text', models.CharField(blank=True, max_length=255, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Auth_Status', models.CharField(blank=True, max_length=1, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_JRNL_LOG_HIST', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_JRNL_LOG_HIST', to='SAMCSYS.mttb_users')),
            ],
            options={
                'verbose_name_plural': 'JRNL_LOG_HIST',
            },
        ),
    ]
