# Generated by Django 5.0.14 on 2025-05-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0015_alter_mttb_function_description_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mttb_function_description',
            options={'ordering': ['Fun_Id'], 'verbose_name_plural': 'Function_Description'},
        ),
        migrations.RenameField(
            model_name='mttb_function_description',
            old_name='Function_Id',
            new_name='Fun_Id',
        ),
        migrations.RemoveField(
            model_name='mttb_role_detail',
            name='Function_Id',
        ),
        migrations.CreateModel(
            name='MTTB_Function_Desc',
            fields=[
                ('Function_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description_la', models.CharField(max_length=200)),
                ('description_en', models.CharField(blank=True, max_length=200, null=True)),
                ('all_link', models.CharField(blank=True, max_length=200, null=True)),
                ('eod_function', models.CharField(blank=True, max_length=1, null=True)),
                ('function_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=30, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('sub_menu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_sub_menu')),
            ],
            options={
                'verbose_name_plural': 'Function_Desc',
                'ordering': ['Function_Id'],
            },
        ),
    ]
