# Generated by Django 5.0.14 on 2025-05-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0016_detb_jrnl_log_hist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTB_DAIRY_LOG',
            fields=[
                ('ac_entry_sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=2)),
                ('trn_ref_no', models.CharField(max_length=16)),
                ('event_sr_no', models.IntegerField(default=0)),
                ('event', models.CharField(blank=True, max_length=4, null=True)),
                ('ac_no', models.CharField(max_length=20)),
                ('ac_ccy', models.CharField(max_length=3)),
                ('drcr_ind', models.CharField(max_length=1)),
                ('trn_code', models.CharField(max_length=3)),
                ('fcy_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('exch_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True)),
                ('lcy_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('external_ref_no', models.CharField(blank=True, max_length=16, null=True)),
                ('addl_text', models.CharField(blank=True, max_length=255, null=True)),
                ('trn_dt', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
                ('category', models.CharField(blank=True, max_length=1, null=True)),
                ('value_dt', models.DateField(blank=True, null=True)),
                ('financial_cycle', models.CharField(blank=True, max_length=9, null=True)),
                ('period_code', models.CharField(blank=True, max_length=3, null=True)),
                ('user_id', models.CharField(blank=True, max_length=12, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('auth_id', models.CharField(blank=True, max_length=12, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Auth_Status', models.CharField(blank=True, max_length=1, null=True)),
                ('product', models.CharField(blank=True, max_length=4, null=True)),
                ('entry_seq_no', models.IntegerField(default=0)),
                ('delete_stat', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'DAILY_LOG',
            },
        ),
    ]
