# Generated by Django 5.0.14 on 2025-05-10 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0016_alter_mttb_function_description_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mttb_role_detail',
            name='Function_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_function_desc'),
        ),
        migrations.AlterField(
            model_name='mttb_function_desc',
            name='Function_Id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Function_Id'),
        ),
    ]
