# Generated by Django 5.0.14 on 2025-05-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0017_mttb_role_detail_function_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STTB_MDdulesInfo',
        ),
    ]
