# Generated by Django 5.0.14 on 2025-05-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0018_actb_dairy_log_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTTB_EOC_MAINTAIN',
            fields=[
                ('eoc_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_id', models.CharField(max_length=2)),
                ('function_id', models.CharField(max_length=8)),
                ('eoc_seq_no', models.IntegerField(default=0)),
                ('eoc_type', models.CharField(max_length=3)),
                ('record_stat', models.CharField(max_length=1)),
                ('mod_no', models.IntegerField(blank=True, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Auth_Status', models.CharField(blank=True, max_length=1, null=True)),
                ('Once_Auth', models.CharField(blank=True, max_length=1, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_EOC_MAINTAIN', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_EOC_MAINTAIN', to='SAMCSYS.mttb_users')),
            ],
            options={
                'verbose_name_plural': 'EOC_MAINTAIN',
            },
        ),
    ]
