# Generated by Django 5.0.14 on 2025-05-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0018_delete_sttb_mddulesinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='STTB_ModulesInfo',
            fields=[
                ('module_id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('M_Id', models.CharField(max_length=50)),
                ('M_NameL', models.CharField(max_length=250)),
                ('M_NameE', models.CharField(max_length=250)),
                ('module_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('module_order', models.CharField(max_length=3)),
                ('is_active', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'ModulesInfo',
            },
        ),
    ]
