# Generated by Django 5.0.14 on 2025-05-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0019_sttb_modulesinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sttb_modulesinfo',
            name='M_Id',
        ),
    ]
