# Generated by Django 5.0.14 on 2025-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0019_mttb_eoc_maintain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actb_dairy_log_history',
            name='entry_seq_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
