# Generated by Django 5.0.14 on 2025-05-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0020_remove_sttb_modulesinfo_m_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sttb_modulesinfo',
            old_name='M_NameE',
            new_name='MODULE_NAMEE',
        ),
        migrations.RenameField(
            model_name='sttb_modulesinfo',
            old_name='M_NameL',
            new_name='MODULE_NAMEL',
        ),
        migrations.AddField(
            model_name='mttb_main_menu',
            name='module_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.sttb_modulesinfo'),
        ),
    ]
