# Generated by Django 5.0.14 on 2025-05-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0020_alter_actb_dairy_log_history_entry_seq_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actb_dairy_log',
            name='entry_seq_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
