# Generated by Django 5.0.14 on 2025-05-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0021_alter_actb_dairy_log_entry_seq_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='STTB_EOC_STATUS',
            fields=[
                ('eoc_stt_id', models.AutoField(primary_key=True, serialize=False)),
                ('eoc_seq_no', models.IntegerField(blank=True, null=True)),
                ('module_id', models.CharField(max_length=2)),
                ('function_id', models.CharField(max_length=8)),
                ('eoc_type', models.CharField(max_length=3)),
                ('eod_date', models.DateTimeField(blank=True, null=True)),
                ('eoc_status', models.CharField(max_length=1)),
                ('error', models.CharField(blank=True, max_length=550, null=True)),
            ],
            options={
                'verbose_name_plural': 'EOC_STATUS',
            },
        ),
    ]
