# Generated by Django 5.0.14 on 2025-05-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0021_rename_m_namee_sttb_modulesinfo_module_namee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_main_menu',
            name='module_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.sttb_modulesinfo', verbose_name='module_id'),
        ),
    ]
