# Generated by Django 5.0.14 on 2025-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0023_sttb_eoc_daily_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='STTB_GL_BAL',
            fields=[
                ('gl_bal_id', models.AutoField(primary_key=True, serialize=False)),
                ('gl_code', models.CharField(blank=True, max_length=20, null=True)),
                ('CCy_Code', models.CharField(blank=True, max_length=20, null=True)),
                ('fin_year', models.CharField(blank=True, max_length=9, null=True)),
                ('period_code', models.CharField(blank=True, max_length=25, null=True)),
                ('category', models.CharField(blank=True, max_length=1, null=True)),
                ('dr_mov', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('cr_mov', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('dr_mov_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('cr_mov_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('dr_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('cr_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('dr_bal_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('cr_bal_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('open_dr_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('open_cr_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('open_dr_bal_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('open_cr_bal_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
            ],
            options={
                'verbose_name_plural': 'GL_BAL',
            },
        ),
    ]
