# Generated by Django 5.0.14 on 2025-05-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0025_sttb_gl_sub_bal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTTB_EMPLOYEE',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_name_la', models.CharField(max_length=250)),
                ('employee_name_en', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('address_la', models.CharField(blank=True, max_length=255, null=True)),
                ('address_en', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('position_code', models.CharField(blank=True, max_length=10, null=True)),
                ('division_id', models.CharField(max_length=20)),
                ('employee_photo', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('employment_status', models.CharField(default='A', max_length=1)),
                ('record_stat', models.CharField(max_length=1)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Auth_Status', models.CharField(blank=True, max_length=1, null=True)),
                ('Once_Auth', models.CharField(blank=True, max_length=1, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_employee', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_employee', to='SAMCSYS.mttb_users')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_users')),
            ],
            options={
                'verbose_name_plural': 'EMPLOYEE',
            },
        ),
    ]
