# Generated by Django 5.0.14 on 2025-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0026_mttb_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
