# Generated by Django 5.0.14 on 2025-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0027_alter_mttb_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_employee',
            name='hire_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
