# Generated by Django 5.0.14 on 2025-05-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0028_alter_mttb_employee_hire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTTB_USER_ACCESS_LOG',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('logout_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('login_status', models.CharField(max_length=1)),
                ('logout_type', models.CharField(blank=True, max_length=1, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_users')),
            ],
            options={
                'verbose_name_plural': 'USER_ACCESS_LOG',
            },
        ),
    ]
