# Generated by Django 5.0.14 on 2025-05-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0029_mttb_user_access_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTTB_USER_ACTIVITY_LOG',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('activity_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('module_id', models.CharField(max_length=10)),
                ('function_id', models.CharField(max_length=20)),
                ('action_type', models.CharField(max_length=20)),
                ('record_id', models.CharField(blank=True, max_length=100, null=True)),
                ('old_values', models.TextField(blank=True, null=True)),
                ('new_values', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_users')),
            ],
        ),
    ]
