# Generated by Django 5.0.14 on 2025-05-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0030_mttb_user_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='mttb_sub_menu',
            name='sub_menu_urls',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
