# Generated by Django 5.0.14 on 2025-05-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0033_mttb_sub_menu_sub_menu_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mttb_function_desc',
            name='all_link',
        ),
    ]
