# Generated by Django 5.0.14 on 2025-05-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0034_remove_mttb_function_desc_all_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancesheet_acc',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('report_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('Pvalue', models.TextField(blank=True, null=True)),
                ('Mvalue', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'balancesheet_acc',
            },
        ),
        migrations.CreateModel(
            name='Balancesheet_mfi',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('report_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('Pvalue', models.TextField(blank=True, null=True)),
                ('Mvalue', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'balancesheet_mfi',
            },
        ),
        migrations.CreateModel(
            name='Incomestatement_acc',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('report_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('Pvalue', models.TextField(blank=True, null=True)),
                ('Mvalue', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'incomestatement_acc',
            },
        ),
        migrations.CreateModel(
            name='Incomestatement_mfi',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('report_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('Pvalue', models.TextField(blank=True, null=True)),
                ('Mvalue', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'incomestatement_mfi',
            },
        ),
    ]
