# Generated by Django 5.0.14 on 2025-05-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0036_alter_mttb_users_maker_dt_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mttb_users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
