# Generated by Django 5.0.14 on 2025-05-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0036_alter_mttb_users_maker_dt_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mttb_users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='mttb_user_access_log',
            name='logout_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_users',
            name='user_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
