# Generated by Django 5.0.14 on 2025-05-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0037_mttb_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_user_access_log',
            name='logout_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_users',
            name='user_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
