# Generated by Django 5.0.14 on 2025-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0037_mttb_users_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('gl_code', models.CharField(blank=True, max_length=50, null=True)),
                ('Desc', models.TextField(blank=True, null=True)),
                ('CCy_Code', models.CharField(blank=True, max_length=20, null=True)),
                ('fin_year', models.CharField(blank=True, max_length=9, null=True)),
                ('period_code', models.CharField(blank=True, max_length=25, null=True)),
                ('category', models.CharField(blank=True, max_length=1, null=True)),
                ('OP_DR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('OP_CR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_DR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_CR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Cl_DR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Cl_CR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('OP_DR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('OP_CR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_DR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_CR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Cl_DR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Cl_CR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('InsertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UserID', models.IntegerField(blank=True, null=True)),
                ('MSegment', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'MonthlyReport',
            },
        ),
    ]
