# Generated by Django 5.0.14 on 2025-05-25 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0039_alter_monthlyreport_ccy_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sttb_gl_bal',
            name='CCy_Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_ccy_defn'),
        ),
        migrations.AlterField(
            model_name='sttb_gl_bal',
            name='fin_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_fin_cycle'),
        ),
        migrations.AlterField(
            model_name='sttb_gl_bal',
            name='gl_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_glmaster'),
        ),
        migrations.AlterField(
            model_name='sttb_gl_bal',
            name='period_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_per_code'),
        ),
    ]
