# Generated by Django 5.0.14 on 2025-05-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0041_alter_sttb_gl_sub_bal_ccy_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sttb_gl_sub_bal',
            name='gl_code',
        ),
        migrations.AddField(
            model_name='sttb_gl_sub_bal',
            name='gl_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_glsub'),
        ),
    ]
