# Generated by Django 5.0.14 on 2025-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0042_remove_sttb_gl_sub_bal_gl_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_users',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_users',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
