# Generated by Django 5.0.14 on 2025-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0043_alter_mttb_users_auth_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actb_dairy_log',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='actb_dairy_log_history',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='detb_jrnl_log',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='detb_jrnl_log_hist',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_ccy_defn',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_ccy_defn',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_ccy_defn',
            name='Record_Status',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_data_entry',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_data_entry',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_data_entry',
            name='Record_Status',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_divisions',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_divisions',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_divisions',
            name='record_Status',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_employee',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_employee',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_eoc_maintain',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_eoc_maintain',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_eoc_maintain',
            name='record_stat',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate',
            name='INT_Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate_history',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_exc_rate_history',
            name='INT_Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_fin_cycle',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_fin_cycle',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_fin_cycle',
            name='Record_Status',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_glmaster',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_glmaster',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_glmaster',
            name='Record_Status',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_glsub',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_glsub',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_glsub',
            name='Record_Status',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_lcl_holiday',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_lcl_holiday',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_lcl_holiday',
            name='Record_Status',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_role_master',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_role_master',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_role_master',
            name='record_Status',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_trn_code',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_trn_code',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_trn_code',
            name='Record_Status',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_eoc_daily_log',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
    ]
