# Generated by Django 5.0.14 on 2025-05-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0044_alter_actb_dairy_log_auth_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_exc_rate_history',
            name='INT_Auth_Status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
