# Generated by Django 5.0.14 on 2025-05-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0045_alter_mttb_exc_rate_history_int_auth_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_function_desc',
            name='eod_function',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_function_desc',
            name='is_active',
            field=models.CharField(blank=True, default='Y', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_modulesinfo',
            name='is_active',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
