# Generated by Django 5.0.14 on 2025-05-27 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0046_alter_mttb_function_desc_eod_function_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mttb_role_detail',
            name='sub_menu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_sub_menu'),
        ),
    ]
