# Generated by Django 5.0.14 on 2025-05-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0047_mttb_role_detail_sub_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mttb_role_detail',
            name='view_Detail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mttb_glmaster',
            name='gl_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
