# Generated by Django 5.0.14 on 2025-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0048_mttb_role_detail_view_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mttb_role_detail',
            old_name='view_Detail',
            new_name='View_Detail',
        ),
        migrations.AlterField(
            model_name='mttb_main_menu',
            name='is_active',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
