# Generated by Django 5.0.14 on 2025-05-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0049_rename_view_detail_mttb_role_detail_view_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_sub_menu',
            name='is_active',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
