# Generated by Django 5.0.14 on 2025-05-29 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0050_alter_mttb_sub_menu_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_employee',
            name='division_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_divisions'),
        ),
    ]
