# Generated by Django 5.0.14 on 2025-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0051_alter_mttb_employee_division_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_employee',
            name='employee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
        migrations.AlterField(
            model_name='mttb_employee',
            name='employee_signature',
            field=models.ImageField(blank=True, null=True, upload_to='employee_signatures/'),
        ),
    ]
