# Generated by Django 5.0.14 on 2025-05-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0052_alter_mttb_employee_employee_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_employee',
            name='record_stat',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
    ]
