# Generated by Django 5.0.14 on 2025-05-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0053_alter_mttb_employee_record_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mttb_employee',
            old_name='division_id',
            new_name='div_id',
        ),
    ]
