# Generated by Django 5.0.14 on 2025-05-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0054_rename_division_id_mttb_employee_div_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mttb_role_detail',
            name='function_id',
        ),
    ]
