# Generated by Django 5.0.14 on 2025-05-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0055_remove_mttb_role_detail_function_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='UpdateDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
