# Generated by Django 5.0.14 on 2025-05-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0056_alter_monthlyreport_updatedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceInfo',
            fields=[
                ('pro_sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.CharField(blank=True, max_length=10, null=True)),
                ('pro_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_name_e', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_name_l', models.CharField(blank=True, max_length=50, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Provinceinfo',
            },
        ),
        migrations.CreateModel(
            name='DistrictInfo',
            fields=[
                ('dis_sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('dis_id', models.CharField(blank=True, max_length=50, null=True)),
                ('dis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('dis_name_e', models.CharField(blank=True, max_length=50, null=True)),
                ('dis_name_l', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('pro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.provinceinfo')),
            ],
            options={
                'verbose_name_plural': 'Districtinfo',
            },
        ),
        migrations.CreateModel(
            name='VillageInfo',
            fields=[
                ('vil_sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('vil_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vil_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vil_name_e', models.CharField(blank=True, max_length=50, null=True)),
                ('vil_name_l', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('vbol_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vbol_name', models.TextField(blank=True, null=True)),
                ('dis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.districtinfo')),
                ('pro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.provinceinfo')),
            ],
            options={
                'verbose_name_plural': 'Villageinfo',
            },
        ),
    ]
