# Generated by Django 5.0.14 on 2025-06-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0057_provinceinfo_districtinfo_villageinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceInfo_new',
            fields=[
                ('pro_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pro_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_name_e', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_name_l', models.CharField(blank=True, max_length=50, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Provinceinfo',
            },
        ),
    ]
