# Generated by Django 5.0.14 on 2025-06-01 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0059_alter_provinceinfo_new_options_districtinfo_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageInfo_new',
            fields=[
                ('vil_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vil_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vil_name_e', models.CharField(blank=True, max_length=50, null=True)),
                ('vil_name_l', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('vbol_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vbol_name', models.TextField(blank=True, null=True)),
                ('dis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.districtinfo_new')),
                ('pro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.provinceinfo_new')),
            ],
            options={
                'verbose_name_plural': 'VillageinfoNew',
            },
        ),
    ]
