# Generated by Django 5.0.14 on 2025-06-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0060_villageinfo_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villageinfo',
            name='dis_id',
        ),
        migrations.RemoveField(
            model_name='villageinfo',
            name='pro_id',
        ),
        migrations.DeleteModel(
            name='DistrictInfo',
        ),
        migrations.DeleteModel(
            name='ProvinceInfo',
        ),
        migrations.DeleteModel(
            name='VillageInfo',
        ),
    ]
