# Generated by Django 5.0.14 on 2025-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0062_provinceinfo_districtinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTTB_ProvincesInfo',
            fields=[
                ('proid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProID', max_length=10, primary_key=True, serialize=False)),
                ('procode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProCode', max_length=50, null=True)),
                ('pronamee', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProNameE', max_length=50, null=True)),
                ('pronamel', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProNameL', max_length=50, null=True)),
                ('dateinsert', models.DateTimeField(blank=True, db_column='DateInsert', null=True)),
                ('dateupdate', models.DateTimeField(blank=True, db_column='DateUpdate', null=True)),
            ],
            options={
                'db_table': 'MTTB_ProvinceInfo',
            },
        ),
        migrations.RemoveField(
            model_name='districtinfo_new',
            name='pro_id',
        ),
        migrations.RemoveField(
            model_name='villageinfo_new',
            name='dis_id',
        ),
        migrations.RemoveField(
            model_name='villageinfo_new',
            name='pro_id',
        ),
        migrations.DeleteModel(
            name='DistrictInfo',
        ),
        migrations.DeleteModel(
            name='ProvinceInfo',
        ),
        migrations.DeleteModel(
            name='DistrictInfo_new',
        ),
        migrations.DeleteModel(
            name='ProvinceInfo_new',
        ),
        migrations.DeleteModel(
            name='VillageInfo_new',
        ),
    ]
