# Generated by Django 5.0.14 on 2025-06-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0063_mttb_provincesinfo_remove_districtinfo_new_pro_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MTTB_ProvincesInfo',
        ),
    ]
