# Generated by Django 5.0.14 on 2025-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0064_delete_mttb_provincesinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTTB_ProvinceInfo',
            fields=[
                ('proid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProID', max_length=10, primary_key=True, serialize=False)),
                ('procode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProCode', max_length=50, null=True)),
                ('pronamee', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProNameE', max_length=50, null=True)),
                ('pronamel', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProNameL', max_length=50, null=True)),
                ('dateinsert', models.DateTimeField(blank=True, db_column='DateInsert', null=True)),
                ('dateupdate', models.DateTimeField(blank=True, db_column='DateUpdate', null=True)),
            ],
        ),
    ]
