# Generated by Django 5.0.14 on 2025-06-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0065_mttb_provinceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTTB_DistrictsInfo',
            fields=[
                ('disid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DisID', max_length=50, primary_key=True, serialize=False)),
                ('discode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DisCode', max_length=50, null=True)),
                ('disnamee', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DisNameE', max_length=50, null=True)),
                ('disnamel', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DisNameL', max_length=50, null=True)),
                ('userid', models.IntegerField(blank=True, db_column='UserID', null=True)),
                ('dateinsert', models.DateTimeField(blank=True, db_column='DateInsert', null=True)),
                ('dateupdate', models.DateTimeField(blank=True, db_column='DateUpdate', null=True)),
                ('province', models.ForeignKey(blank=True, db_column='ProID', null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_provinceinfo')),
            ],
        ),
    ]
