# Generated by Django 5.0.14 on 2025-06-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0067_mttb_villagesinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MTTB_DistrictsInfo',
            new_name='MTTB_DistrictInfo',
        ),
        migrations.RenameModel(
            old_name='MTTB_VillagesInfo',
            new_name='MTTB_VillageInfo',
        ),
    ]
