# Generated by Django 5.0.14 on 2025-06-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0068_rename_mttb_districtsinfo_mttb_districtinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_districtinfo',
            name='discode',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DisCode', default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mttb_districtinfo',
            name='disid',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DisID', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='MTTB_VillageInfo',
        ),
    ]
