# Generated by Django 5.0.14 on 2025-06-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0069_alter_mttb_districtinfo_discode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MTTB_DistrictInfo',
        ),
    ]
