# Generated by Django 5.0.14 on 2025-06-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0070_delete_mttb_districtinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MTTB_ProvinceInfo',
        ),
    ]
