# Generated by Django 5.0.14 on 2025-06-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0072_provinceinfos_districtinfos_villageinfos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villageinfos',
            name='district',
        ),
        migrations.RemoveField(
            model_name='villageinfos',
            name='province',
        ),
        migrations.DeleteModel(
            name='DistrictInfos',
        ),
        migrations.DeleteModel(
            name='ProvinceInfos',
        ),
        migrations.DeleteModel(
            name='VillageInfos',
        ),
    ]
