# Generated by Django 5.0.14 on 2025-06-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0073_remove_villageinfos_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTTB_ProvinceInfo',
            fields=[
                ('pro_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pro_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_name_e', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_name_l', models.CharField(blank=True, max_length=50, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
