# Generated by Django 5.0.14 on 2025-06-02 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0074_mttb_provinceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictInfos',
            fields=[
                ('dis_id', models.CharField(blank=True, max_length=50, null=True)),
                ('dis_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dis_name_e', models.CharField(blank=True, max_length=50, null=True)),
                ('dis_name_l', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='SAMCSYS.mttb_provinceinfo')),
            ],
        ),
    ]
