# Generated by Django 5.0.14 on 2025-06-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0075_districtinfos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistrictInfos',
            new_name='MTTB_DistrictInfo',
        ),
    ]
