# Generated by Django 5.0.14 on 2025-06-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0077_mttb_villageinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_villageinfo',
            name='vil_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_villageinfo',
            name='vil_id',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
