# Generated by Django 5.0.14 on 2025-06-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0078_alter_mttb_villageinfo_vil_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_lcl_holiday',
            name='Holiday_List',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
