# Generated by Django 5.0.14 on 2025-06-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0079_alter_mttb_lcl_holiday_holiday_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MTTB_VillageInfo',
        ),
    ]
