# Generated by Django 5.0.14 on 2025-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0081_mttb_villageinfo_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_villageinfo_map',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
