# Generated by Django 5.0.14 on 2025-06-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0083_delete_mttb_villageinfo_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MTTB_DistrictInfo',
        ),
    ]
