# Generated by Django 5.0.14 on 2025-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0085_delete_mttb_provinceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTTB_DistrictInfo',
            fields=[
                ('dis_sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.CharField(blank=True, max_length=10, null=True)),
                ('dis_id', models.CharField(blank=True, max_length=50, null=True)),
                ('dis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('dis_name_e', models.CharField(blank=True, max_length=50, null=True)),
                ('dis_name_l', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Districtinfo',
            },
        ),
        migrations.CreateModel(
            name='MTTB_ProvinceInfo',
            fields=[
                ('pro_sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.CharField(blank=True, max_length=10, null=True)),
                ('pro_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_name_e', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_name_l', models.CharField(blank=True, max_length=50, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Provinceinfo',
            },
        ),
        migrations.CreateModel(
            name='MTTB_VillageInfo',
            fields=[
                ('vil_sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.CharField(blank=True, max_length=10, null=True)),
                ('dis_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vil_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vil_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vil_name_e', models.CharField(blank=True, max_length=50, null=True)),
                ('vil_name_l', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('vbol_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vbol_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Villageinfo',
            },
        ),
    ]
