# Generated by Django 5.0.14 on 2025-06-04 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0086_mttb_districtinfo_mttb_provinceinfo_mttb_villageinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_asset_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_tangible', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('type_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('type_name_la', models.CharField(blank=True, max_length=255, null=True)),
                ('type_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('create_datetime', models.DateTimeField(blank=True, null=True)),
                ('update_datetime', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_assest_type', to='SAMCSYS.mttb_users')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_assest_type', to='SAMCSYS.mttb_users')),
            ],
            options={
                'verbose_name_plural': 'AssestType',
            },
        ),
    ]
