# Generated by Django 5.0.14 on 2025-06-05 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0087_fa_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_glmaster',
            name='Res_ccy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_ccy_defn'),
        ),
    ]
