# Generated by Django 5.0.14 on 2025-06-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0088_alter_mttb_glmaster_res_ccy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detb_jrnl_log_hist',
            name='Checker_Id',
        ),
        migrations.RemoveField(
            model_name='detb_jrnl_log_hist',
            name='Maker_Id',
        ),
        migrations.DeleteModel(
            name='DETB_JRNL_LOG',
        ),
        migrations.DeleteModel(
            name='DETB_JRNL_LOG_HIST',
        ),
    ]
