# Generated by Django 5.0.14 on 2025-06-06 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0089_remove_detb_jrnl_log_hist_checker_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETB_JRNL_LOG',
            fields=[
                ('JRNLLog_id', models.AutoField(primary_key=True, serialize=False)),
                ('Reference_No', models.CharField(max_length=20)),
                ('Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('Lcy_Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('Dr_cr', models.CharField(max_length=1)),
                ('Value_date', models.DateTimeField(blank=True, null=True)),
                ('Exch_rate', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('Addl_text', models.CharField(blank=True, max_length=255, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Auth_Status', models.CharField(blank=True, default='U', max_length=1, null=True)),
                ('Account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_glsub')),
                ('Ccy_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_ccy_defn')),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_JRNL_LOG', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_JRNL_LOG', to='SAMCSYS.mttb_users')),
                ('Period_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_per_code')),
                ('Txn_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_trn_code')),
                ('fin_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_fin_cycle')),
            ],
            options={
                'verbose_name_plural': 'JRNL_LOG',
            },
        ),
        migrations.CreateModel(
            name='DETB_JRNL_LOG_HIST',
            fields=[
                ('Reference_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('Lcy_Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('Dr_cr', models.CharField(max_length=1)),
                ('Value_date', models.DateTimeField(blank=True, null=True)),
                ('Exch_rate', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('Addl_text', models.CharField(blank=True, max_length=255, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Auth_Status', models.CharField(blank=True, default='U', max_length=1, null=True)),
                ('Account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_glsub')),
                ('Ccy_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_ccy_defn')),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_JRNL_LOG_HIST', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_JRNL_LOG_HIST', to='SAMCSYS.mttb_users')),
                ('Period_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_per_code')),
                ('Txn_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_trn_code')),
                ('fin_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_fin_cycle')),
            ],
            options={
                'verbose_name_plural': 'JRNL_LOG_HIST',
            },
        ),
    ]
