# Generated by Django 5.0.14 on 2025-06-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0089_alter_mttb_data_entry_back_value_and_more'),
        ('SAMCSYS', '0092_actb_dairy_log_actb_dairy_log_history'),
    ]

    operations = [
    ]
