# Generated by Django 5.0.14 on 2025-06-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0093_merge_20250607_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='actb_dairy_log',
            name='ac_relative',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log',
            name='fcy_cr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log',
            name='fcy_dr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log',
            name='lcy_cr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log',
            name='lcy_dr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log_history',
            name='ac_relative',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log_history',
            name='fcy_cr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log_history',
            name='fcy_dr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log_history',
            name='lcy_cr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log_history',
            name='lcy_dr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='detb_jrnl_log',
            name='Reference_No',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
