# Generated by Django 5.0.14 on 2025-06-07 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0096_detb_jrnl_log_hist_ac_relative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detb_jrnl_log',
            name='module_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.sttb_modulesinfo'),
        ),
        migrations.AddField(
            model_name='detb_jrnl_log_hist',
            name='module_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.sttb_modulesinfo'),
        ),
    ]
