# Generated by Django 5.0.14 on 2025-06-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0097_detb_jrnl_log_module_id_detb_jrnl_log_hist_module_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detb_jrnl_log',
            old_name='Amount',
            new_name='Fcy_Amount',
        ),
    ]
