# Generated by Django 5.0.14 on 2025-06-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0098_rename_amount_detb_jrnl_log_fcy_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detb_jrnl_log',
            name='Reference_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='detb_jrnl_log',
            unique_together={('Reference_No', 'Account', 'Dr_cr', 'Fcy_Amount')},
        ),
        migrations.AddConstraint(
            model_name='detb_jrnl_log',
            constraint=models.UniqueConstraint(fields=('Reference_No', 'Account', 'Dr_cr', 'Fcy_Amount'), name='unique_journal_entry'),
        ),
    ]
