# Generated by Django 5.0.14 on 2025-06-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0099_alter_detb_jrnl_log_reference_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detb_jrnl_log_hist',
            old_name='ac_relative',
            new_name='Ac_relative',
        ),
    ]
