# Generated by Django 5.0.14 on 2025-06-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0100_rename_ac_relative_detb_jrnl_log_hist_ac_relative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detb_jrnl_log',
            name='ac_relative',
        ),
    ]
