# Generated by Django 5.0.14 on 2025-06-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0101_remove_detb_jrnl_log_ac_relative'),
    ]

    operations = [
        migrations.AddField(
            model_name='detb_jrnl_log',
            name='Ac_relatives',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
