# Generated by Django 5.0.14 on 2025-06-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0102_detb_jrnl_log_ac_relatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='detb_jrnl_log',
            name='Addl_sub_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
