# Generated by Django 5.0.14 on 2025-06-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0103_detb_jrnl_log_addl_sub_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='detb_jrnl_log',
            name='Account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
