# Generated by Django 5.0.14 on 2025-06-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0105_detb_jrnl_log_master'),
        ('SAMCSYS', '0105_mttb_glmaster_categorytype'),
    ]

    operations = [
    ]
