# Generated by Django 5.0.14 on 2025-06-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0107_rename_amount_detb_jrnl_log_hist_fcy_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detb_jrnl_log_hist',
            old_name='Ac_relative',
            new_name='Ac_relatives',
        ),
        migrations.AddField(
            model_name='detb_jrnl_log_hist',
            name='Account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
