# Generated by Django 5.0.14 on 2025-06-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0108_rename_ac_relative_detb_jrnl_log_hist_ac_relatives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detb_jrnl_log_hist',
            name='Account_no',
        ),
    ]
