# Generated by Django 5.0.14 on 2025-06-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0109_remove_detb_jrnl_log_hist_account_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sttb_modulesinfo',
            old_name='modified_date',
            new_name='Checker_DT_Stamp',
        ),
        migrations.RenameField(
            model_name='sttb_modulesinfo',
            old_name='created_by',
            new_name='Checker_Id',
        ),
        migrations.RenameField(
            model_name='sttb_modulesinfo',
            old_name='created_date',
            new_name='Maker_DT_Stamp',
        ),
        migrations.RenameField(
            model_name='sttb_modulesinfo',
            old_name='modified_by',
            new_name='Maker_Id',
        ),
        migrations.RenameField(
            model_name='sttb_modulesinfo',
            old_name='is_active',
            new_name='Record_Status',
        ),
        migrations.AddField(
            model_name='sttb_modulesinfo',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='sttb_modulesinfo',
            name='Once_Auth',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
