# Generated by Django 5.0.14 on 2025-06-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0112_rename_modified_date_mttb_sub_menu_checker_dt_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_main_menu',
            name='Record_Status',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='mttb_sub_menu',
            name='Record_Status',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='sttb_modulesinfo',
            name='Record_Status',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
