# Generated by Django 5.0.14 on 2025-06-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0113_alter_mttb_main_menu_record_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detb_jrnl_log_hist',
            name='Account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
