# Generated by Django 5.0.14 on 2025-06-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0113_alter_mttb_main_menu_record_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FA_asset_type',
        ),
    ]
