# Generated by Django 5.0.14 on 2025-06-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0114_delete_fa_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Asset_Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_code', models.CharField(blank=True, max_length=10, null=True)),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_type', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_type', to='SAMCSYS.mttb_users')),
            ],
            options={
                'verbose_name_plural': 'AssestType',
            },
        ),
    ]
