# Generated by Django 5.0.14 on 2025-06-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0114_detb_jrnl_log_hist_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='detb_jrnl_log_hist',
            name='JRNLLog_id_his',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detb_jrnl_log_hist',
            name='Reference_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
