# Generated by Django 5.0.14 on 2025-06-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0115_detb_jrnl_log_hist_jrnllog_id_his_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DETB_JRNL_LOG_HIST',
        ),
    ]
