# Generated by Django 5.0.14 on 2025-06-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0117_detb_jrnl_log_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detb_jrnl_log',
            name='Reference_No',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detb_jrnl_log_history',
            name='JRNLLog_id_his',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
