# Generated by Django 5.0.14 on 2025-06-16 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0117_fa_asset_accountofasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Transaction_TypeOfAsset',
            fields=[
                ('tran_id', models.AutoField(primary_key=True, serialize=False)),
                ('tran_name_la', models.CharField(blank=True, max_length=250, null=True)),
                ('tran_name_en', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_transaction_type_ofasset', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_transaction_type_ofasset', to='SAMCSYS.mttb_users')),
            ],
            options={
                'verbose_name_plural': 'TransactionTypeOfAsset',
            },
        ),
    ]
