# Generated by Django 5.0.14 on 2025-06-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0118_alter_detb_jrnl_log_reference_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detb_jrnl_log_history',
            name='JRNLLog_id_his',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
