# Generated by Django 5.0.14 on 2025-06-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0118_fa_transaction_typeofasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Asset_List',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_code', models.CharField(blank=True, max_length=20, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('useful_life', models.IntegerField(blank=True, null=True)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_date', models.DateField(blank=True, null=True)),
                ('lasst_maintenance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='InProgress', max_length=20, null=True)),
                ('accumulated_depreciation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_list', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_list', to='SAMCSYS.mttb_users')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_suppliers')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_type')),
            ],
            options={
                'verbose_name_plural': 'AssestList',
            },
        ),
    ]
