# Generated by Django 5.0.14 on 2025-06-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0119_alter_detb_jrnl_log_history_jrnllog_id_his'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DETB_JRNL_LOG_HISTORY',
        ),
    ]
