# Generated by Django 5.0.14 on 2025-06-17 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0120_delete_detb_jrnl_log_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETB_JRNL_LOG_HIST',
            fields=[
                ('JRNLLog_id_his', models.AutoField(primary_key=True, serialize=False)),
                ('Reference_No', models.CharField(blank=True, max_length=20, null=True)),
                ('Fcy_Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('Lcy_Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('fcy_dr', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('fcy_cr', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('lcy_dr', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('lcy_cr', models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True)),
                ('Dr_cr', models.CharField(max_length=1)),
                ('Account_no', models.CharField(blank=True, max_length=30, null=True)),
                ('Ac_relatives', models.CharField(blank=True, max_length=50, null=True)),
                ('Value_date', models.DateTimeField(blank=True, null=True)),
                ('Exch_rate', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('Addl_text', models.CharField(blank=True, max_length=255, null=True)),
                ('Addl_sub_text', models.CharField(blank=True, max_length=255, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Auth_Status', models.CharField(blank=True, default='U', max_length=1, null=True)),
                ('Account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_glsub')),
                ('Ccy_cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_ccy_defn')),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_JRNL_LOG_HIST', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_JRNL_LOG_HIST', to='SAMCSYS.mttb_users')),
                ('Period_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_per_code')),
                ('Txn_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_trn_code')),
                ('fin_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_fin_cycle')),
                ('module_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.sttb_modulesinfo')),
            ],
            options={
                'verbose_name_plural': 'JRNL_LOG_HIST',
            },
        ),
    ]
