# Generated by Django 5.0.14 on 2025-06-16 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0120_fa_asset_list_disposal_acc_mothod'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Asset_Transaction',
            fields=[
                ('at_id', models.AutoField(primary_key=True, serialize=False)),
                ('assetTransaction_name_la', models.CharField(blank=True, max_length=250, null=True)),
                ('assetTransaction_name_en', models.CharField(blank=True, max_length=250, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('warranty_date', models.DateField(blank=True, null=True)),
                ('asset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_suppliers')),
            ],
            options={
                'verbose_name_plural': 'AssestTransaction',
            },
        ),
    ]
