# Generated by Django 5.0.14 on 2025-06-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0121_detb_jrnl_log_hist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sttb_dates',
            old_name='insertToday',
            new_name='Start_Date',
        ),
    ]
