# Generated by Django 5.0.14 on 2025-06-16 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0121_fa_asset_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Asset_Of_Activity',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_code', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('debit_account_id', models.IntegerField(blank=True, null=True)),
                ('credit_account_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_of_activity', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_of_activity', to='SAMCSYS.mttb_users')),
                ('asset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list')),
            ],
            options={
                'verbose_name_plural': 'AssestOfActivity',
            },
        ),
    ]
