# Generated by Django 5.0.14 on 2025-06-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0122_fa_asset_of_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fa_asset_of_activity',
            name='type_code',
        ),
    ]
