# Generated by Django 5.0.14 on 2025-06-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0123_remove_fa_asset_of_activity_type_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Depreciation',
            fields=[
                ('depreciation_id', models.AutoField(primary_key=True, serialize=False)),
                ('depreciation_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('method', models.CharField(blank=True, max_length=250, null=True)),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('remaining_life', models.IntegerField(blank=True, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('period_year', models.CharField(blank=True, max_length=4, null=True)),
                ('period_month', models.CharField(blank=True, max_length=7, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_depreciation', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_depreciation', to='SAMCSYS.mttb_users')),
                ('asset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list')),
                ('transaction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_of_activity')),
            ],
            options={
                'verbose_name_plural': 'Depreciation',
            },
        ),
    ]
