# Generated by Django 5.0.14 on 2025-06-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0124_fa_depreciation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FA_Depreciation',
            new_name='FA_Asset_Depreciation',
        ),
        migrations.CreateModel(
            name='FA_Asset_Disposal_Logs',
            fields=[
                ('disposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_type', models.CharField(blank=True, max_length=100, null=True)),
                ('proceeds', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('disposal_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gain_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_disposal_logs', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_disposal_logs', to='SAMCSYS.mttb_users')),
                ('asset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list')),
                ('transaction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_transaction')),
            ],
            options={
                'verbose_name_plural': 'AssestDisposalLogs',
            },
        ),
    ]
