# Generated by Django 5.0.14 on 2025-06-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0126_fa_asset_maintenance_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Asset_Transfer_Logs',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('from_department_id', models.CharField(blank=True, max_length=100, null=True)),
                ('to_department_id', models.CharField(blank=True, max_length=100, null=True)),
                ('from_location', models.CharField(blank=True, max_length=100, null=True)),
                ('to_location', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_reason', models.TextField(blank=True, null=True)),
                ('transfer_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('condition_before', models.TextField(blank=True, null=True)),
                ('condition_after', models.TextField(blank=True, null=True)),
                ('transport_method', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_transfer_logs', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_transfer_logs', to='SAMCSYS.mttb_users')),
                ('asset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list')),
                ('transaction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_transaction')),
            ],
            options={
                'verbose_name_plural': 'AssestTransferLogs',
            },
        ),
    ]
