# Generated by Django 5.0.14 on 2025-06-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0122_rename_inserttoday_sttb_dates_start_date'),
        ('SAMCSYS', '0127_fa_asset_transfer_logs'),
    ]

    operations = [
    ]
