# Generated by Django 5.0.14 on 2025-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0128_merge_20250617_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='actb_dairy_log',
            name='ac_no_full',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log',
            name='addl_sub_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
