# Generated by Django 5.0.14 on 2025-06-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0129_actb_dairy_log_ac_no_full_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actb_dairy_log',
            name='external_ref_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='actb_dairy_log_history',
            name='external_ref_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
