# Generated by Django 5.0.14 on 2025-06-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0130_alter_actb_dairy_log_external_ref_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mttb_role_detail',
            name='Record_Status',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
    ]
