# Generated by Django 5.0.14 on 2025-06-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0131_mttb_role_detail_record_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mttb_divisions',
            old_name='record_Status',
            new_name='Record_Status',
        ),
    ]
