# Generated by Django 5.0.14 on 2025-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0132_rename_record_status_mttb_divisions_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='actb_dairy_log_history',
            name='ac_no_full',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log_history',
            name='addl_sub_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
