# Generated by Django 5.0.14 on 2025-06-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0133_actb_dairy_log_history_ac_no_full_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actb_dairy_log',
            old_name='type',
            new_name='glid',
        ),
        migrations.RenameField(
            model_name='actb_dairy_log_history',
            old_name='type',
            new_name='glid',
        ),
    ]
