# Generated by Django 5.0.14 on 2025-06-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0134_rename_type_actb_dairy_log_glid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actb_dairy_log_history',
            name='glType',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
