# Generated by Django 5.0.14 on 2025-06-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0136_remove_fa_asset_depreciation_checker_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fa_asset_type',
            old_name='record_Status',
            new_name='Record_Status',
        ),
        migrations.RenameField(
            model_name='fa_asset_type',
            old_name='type_name',
            new_name='type_name_en',
        ),
        migrations.RemoveField(
            model_name='fa_asset_type',
            name='description',
        ),
        migrations.AddField(
            model_name='fa_asset_type',
            name='is_tangible',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='fa_asset_type',
            name='type_name_la',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
