# Generated by Django 5.0.14 on 2025-06-18 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0137_rename_record_status_fa_asset_type_record_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Chart_Of_Asset',
            fields=[
                ('coa_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_code', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_name_la', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_chart_of_asset', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_chart_of_asset', to='SAMCSYS.mttb_users')),
                ('asset_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_type')),
            ],
            options={
                'verbose_name_plural': 'ChartOfAsset',
            },
        ),
    ]
