# Generated by Django 5.0.14 on 2025-06-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0139_fa_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_code', models.CharField(blank=True, max_length=20, null=True)),
                ('location_name_la', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_location_id', models.IntegerField(blank=True, null=True)),
                ('location_type', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_locations', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_locations', to='SAMCSYS.mttb_users')),
            ],
            options={
                'verbose_name_plural': 'AssetLocations',
            },
        ),
    ]
