# Generated by Django 5.0.14 on 2025-06-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0140_fa_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Expense_Category',
            fields=[
                ('ec_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_code', models.CharField(blank=True, max_length=20, null=True)),
                ('category_name_la', models.CharField(blank=True, max_length=255, null=True)),
                ('category_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('is_capitalized_default', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('default_gl_account', models.CharField(blank=True, max_length=50, null=True)),
                ('required_approval', models.CharField(blank=True, default='Y', max_length=1, null=True)),
                ('approval_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_expense_category', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_expense_category', to='SAMCSYS.mttb_users')),
            ],
            options={
                'verbose_name_plural': 'ExpenseCategory',
            },
        ),
    ]
