# Generated by Django 5.0.14 on 2025-06-18 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0143_fa_depreciation_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Depreciation_Sub',
            fields=[
                ('ds_id', models.AutoField(primary_key=True, serialize=False)),
                ('round_no', models.IntegerField(blank=True, null=True)),
                ('dpca_date', models.DateField(blank=True, null=True)),
                ('dpca_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dpca_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dpca_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dpca_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dpca_yesno', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('period_year', models.CharField(blank=True, max_length=4, null=True)),
                ('period_month', models.CharField(blank=True, max_length=7, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('approve_datetime', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_depreciation_sub', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_depreciation_sub', to='SAMCSYS.mttb_users')),
                ('approve_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_depreciation_sub', to='SAMCSYS.mttb_users')),
                ('m_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_depreciation_main')),
            ],
            options={
                'verbose_name_plural': 'DepreciationSub',
            },
        ),
    ]
