# Generated by Django 5.0.14 on 2025-06-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0144_fa_depreciation_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fa_depreciation_sub',
            name='create_date',
        ),
        migrations.CreateModel(
            name='FA_Asset_List_Depreciation',
            fields=[
                ('ald_id', models.AutoField(primary_key=True, serialize=False)),
                ('dpca_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dpca_no_of_days', models.IntegerField(blank=True, null=True)),
                ('remaining_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('accumulated_dpca', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dpca_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('dpca_ac_yesno', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('dpca_date', models.DateField(blank=True, null=True)),
                ('dpca_datetime', models.DateTimeField(blank=True, null=True)),
                ('dpca_ac_by', models.IntegerField(blank=True, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_list_depreciation', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_list_depreciation', to='SAMCSYS.mttb_users')),
                ('asset_list_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list')),
            ],
            options={
                'verbose_name_plural': 'AssestListDepreciation',
            },
        ),
    ]
