# Generated by Django 5.0.14 on 2025-06-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0145_remove_fa_depreciation_sub_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Asset_List_Disposal',
            fields=[
                ('alds_id', models.AutoField(primary_key=True, serialize=False)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_type', models.CharField(blank=True, max_length=20, null=True)),
                ('disposal_by', models.IntegerField(blank=True, null=True)),
                ('disposal_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('disposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('disposal_proceeds', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('disposal_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gain_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('disposal_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('disposal_ac_yesno', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('disposal_ac_date', models.DateField(blank=True, null=True)),
                ('disposal_ac_datetime', models.DateTimeField(blank=True, null=True)),
                ('disposal_ac_by', models.IntegerField(blank=True, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_list_disposal', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_list_disposal', to='SAMCSYS.mttb_users')),
                ('asset_list_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list')),
            ],
            options={
                'verbose_name_plural': 'AssestListDisposal',
            },
        ),
    ]
