# Generated by Django 5.0.14 on 2025-06-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0146_fa_asset_list_disposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Asset_Expense',
            fields=[
                ('ae_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_type', models.CharField(blank=True, max_length=50, null=True)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=5, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('expense_amount_base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('expense_description', models.TextField(blank=True, null=True)),
                ('is_capitalized', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('warranty_coverd', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('downtime_hours', models.IntegerField(blank=True, null=True)),
                ('expense_status', models.CharField(blank=True, default='PENDING', max_length=20, null=True)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_posted', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('posted_by', models.IntegerField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('journal_entry_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_expense', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_expense', to='SAMCSYS.mttb_users')),
                ('asset_list_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list')),
                ('vendore_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_suppliers')),
            ],
            options={
                'verbose_name_plural': 'AssestExpense',
            },
        ),
    ]
