# Generated by Django 5.0.14 on 2025-06-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0147_fa_asset_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Transfer_Logs',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_reason', models.TextField(blank=True, null=True)),
                ('transfer_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('condition_before', models.TextField(blank=True, null=True)),
                ('condition_after', models.TextField(blank=True, null=True)),
                ('transport_method', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_by', models.IntegerField(blank=True, null=True)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('received_by', models.IntegerField(blank=True, null=True)),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_covered', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_transfer_logs', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_transfer_logs', to='SAMCSYS.mttb_users')),
                ('asset_list_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list')),
                ('from_location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from_location', to='SAMCSYS.fa_location')),
                ('to_location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to_location', to='SAMCSYS.fa_location')),
            ],
            options={
                'verbose_name_plural': 'TransferLogs',
            },
        ),
    ]
