# Generated by Django 5.0.14 on 2025-06-18 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0149_fa_asset_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Maintenance_Logs',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_type', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency_id', models.CharField(blank=True, default='LAK', max_length=5, null=True)),
                ('technician', models.CharField(blank=True, max_length=100, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, default='MEDIUM', null=True)),
                ('downtime_hours', models.IntegerField(blank=True, null=True)),
                ('severity_level', models.CharField(blank=True, max_length=20, null=True)),
                ('warranty_claim', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('status', models.CharField(blank=True, default='SCHEDULED', max_length=50, null=True)),
                ('completed_by', models.IntegerField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_maintenance_logs', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_maintenance_logs', to='SAMCSYS.mttb_users')),
                ('asset_list_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_suppliers')),
            ],
            options={
                'verbose_name_plural': 'MaintenanceLogs',
            },
        ),
    ]
