# Generated by Django 5.0.14 on 2025-06-18 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0150_fa_maintenance_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Accounting_Method',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('acc_type', models.CharField(blank=True, max_length=50, null=True)),
                ('debit_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('journal_entry_id', models.CharField(blank=True, max_length=50, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_accounting_method', to='SAMCSYS.mttb_users')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_accounting_method', to='SAMCSYS.mttb_users')),
                ('asset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list')),
            ],
            options={
                'verbose_name_plural': 'AccountingMethod',
            },
        ),
    ]
