# Generated by Django 5.0.14 on 2025-06-19 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0151_fa_accounting_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTTB_REVOKED_SESSIONS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('revoked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_sessions', to='SAMCSYS.mttb_users')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_users')),
            ],
            options={
                'verbose_name_plural': 'Revoked Sessions',
                'db_table': 'mttb_revoked_sessions',
                'indexes': [models.Index(fields=['jti'], name='mttb_revoke_jti_63cdf2_idx'), models.Index(fields=['user_id'], name='mttb_revoke_user_id_3742f4_idx'), models.Index(fields=['revoked_at'], name='mttb_revoke_revoked_7c030e_idx')],
            },
        ),
    ]
