# Generated by Django 5.0.14 on 2025-06-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0152_mttb_revoked_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_user_access_log',
            name='login_status',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Failed'), ('A', 'Admin Action')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mttb_user_access_log',
            name='logout_type',
            field=models.CharField(blank=True, choices=[('U', 'User Initiated'), ('F', 'Force Logout'), ('T', 'Timeout'), ('S', 'System')], max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='mttb_user_access_log',
            index=models.Index(fields=['user_id', 'logout_datetime'], name='mttb_user_a_user_id_89887f_idx'),
        ),
        migrations.AddIndex(
            model_name='mttb_user_access_log',
            index=models.Index(fields=['session_id'], name='mttb_user_a_session_ff2802_idx'),
        ),
        migrations.AddIndex(
            model_name='mttb_user_access_log',
            index=models.Index(fields=['login_datetime'], name='mttb_user_a_login_d_23803f_idx'),
        ),
        migrations.AlterModelTable(
            name='mttb_user_access_log',
            table='mttb_user_access_log',
        ),
        migrations.AlterModelTable(
            name='mttb_users',
            table='SAMCSYS_mttb_users',
        ),
    ]
