# Generated by Django 5.0.14 on 2025-06-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0154_mttb_users_groups_mttb_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mttb_revoked_sessions',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
