# Generated by Django 5.0.14 on 2025-06-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0154_mttb_users_groups_mttb_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fa_asset_list',
            old_name='al_id',
            new_name='asset_list_id',
        ),
    ]
