# Generated by Django 5.0.14 on 2025-06-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0155_rename_al_id_fa_asset_list_asset_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_asset_list',
            name='asset_serial_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fa_asset_list',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
