# Generated by Django 5.0.14 on 2025-06-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0156_alter_fa_asset_list_asset_serial_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_asset_type',
            name='type_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
