# Generated by Django 5.0.14 on 2025-06-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0157_alter_fa_asset_type_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_chart_of_asset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fa_expense_category',
            name='category_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fa_location',
            name='location_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fa_suppliers',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
