# Generated by Django 5.0.14 on 2025-06-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0158_alter_fa_chart_of_asset_asset_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fa_asset_list',
            old_name='asset_id',
            new_name='asset_type_id',
        ),
        migrations.AddField(
            model_name='fa_asset_list',
            name='asset_list_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
