# Generated by Django 5.0.14 on 2025-06-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0155_mttb_revoked_sessions_ip_address'),
        ('SAMCSYS', '0158_alter_fa_chart_of_asset_asset_code_and_more'),
    ]

    operations = [
    ]
