# Generated by Django 5.0.14 on 2025-06-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0159_merge_20250621_1411'),
        ('SAMCSYS', '0159_rename_asset_id_fa_asset_list_asset_type_id_and_more'),
    ]

    operations = [
    ]
