# Generated by Django 5.0.14 on 2025-06-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0161_alter_mttb_eoc_maintain_function_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mttb_eoc_maintain',
            old_name='record_stat',
            new_name='Record_Status',
        ),
    ]
