# Generated by Django 5.0.14 on 2025-06-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0162_rename_record_stat_mttb_eoc_maintain_record_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mttb_function_desc',
            name='sub_menu_id',
        ),
    ]
