# Generated by Django 5.0.14 on 2025-06-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0163_remove_mttb_function_desc_sub_menu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mttb_function_desc',
            old_name='created_by',
            new_name='Checker_Id',
        ),
        migrations.RenameField(
            model_name='mttb_function_desc',
            old_name='created_date',
            new_name='Maker_DT_Stamp',
        ),
        migrations.RenameField(
            model_name='mttb_function_desc',
            old_name='modified_by',
            new_name='Maker_Id',
        ),
        migrations.RenameField(
            model_name='mttb_function_desc',
            old_name='is_active',
            new_name='Record_Status',
        ),
        migrations.RemoveField(
            model_name='mttb_function_desc',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='mttb_function_desc',
            name='Checker_DT_Stamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
