# Generated by Django 5.0.14 on 2025-06-22 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0164_rename_created_by_mttb_function_desc_checker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_function_desc',
            name='Checker_DT_Stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mttb_function_desc',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_userss', to='SAMCSYS.mttb_function_desc'),
        ),
        migrations.AlterField(
            model_name='mttb_function_desc',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_userss', to='SAMCSYS.mttb_function_desc'),
        ),
    ]
