# Generated by Django 5.0.14 on 2025-06-22 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0165_alter_mttb_function_desc_checker_dt_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_function_desc',
            name='Checker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_functions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mttb_function_desc',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_functions', to=settings.AUTH_USER_MODEL),
        ),
    ]
