# Generated by Django 5.0.14 on 2025-06-22 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0166_alter_mttb_function_desc_checker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_monthlyreport', to=settings.AUTH_USER_MODEL),
        ),
    ]
