# Generated by Django 5.0.14 on 2025-06-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0167_alter_monthlyreport_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fa_accounting_method',
            old_name='asset_id',
            new_name='asset_list_id',
        ),
    ]
