# Generated by Django 5.0.14 on 2025-06-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0168_rename_asset_id_fa_accounting_method_asset_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mttb_glmaster',
            name='mod_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mttb_glmaster',
            name='outstanding',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mttb_glmaster',
            name='post_side',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
