# Generated by Django 5.0.14 on 2025-06-23 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0169_mttb_glmaster_mod_no_mttb_glmaster_outstanding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Asset_Lists',
            fields=[
                ('asset_list_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('asset_list_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('asset_serial_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('asset_tag', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('asset_spec', models.TextField(blank=True, null=True)),
                ('asset_date', models.DateField(blank=True, null=True)),
                ('asset_currency', models.CharField(blank=True, max_length=5, null=True)),
                ('asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('asset_status', models.CharField(blank=True, default='ACTIVE', max_length=20, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('has_depreciation', models.CharField(blank=True, default='Y', max_length=1, null=True)),
                ('dpca_type', models.CharField(blank=True, max_length=20, null=True)),
                ('dpca_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('asset_useful_life', models.IntegerField(blank=True, null=True)),
                ('asset_salvage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dpca_start_date', models.DateField(blank=True, null=True)),
                ('dpca_end_date', models.DateField(blank=True, null=True)),
                ('asset_accu_dpca_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('asset_value_remain', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('asset_latest_date_dpca', models.DateField(blank=True, null=True)),
                ('asset_disposal_date', models.DateField(blank=True, null=True)),
                ('asset_ac_yesno', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('asset_ac_date', models.DateField(blank=True, null=True)),
                ('asset_ac_datetime', models.DateTimeField(blank=True, null=True)),
                ('aaset_ac_by', models.IntegerField(blank=True, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_lists', to=settings.AUTH_USER_MODEL)),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_lists', to=settings.AUTH_USER_MODEL)),
                ('asset_location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_location')),
                ('asset_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_chart_of_asset')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_suppliers')),
            ],
            options={
                'verbose_name_plural': 'AssestLists',
            },
        ),
    ]
