# Generated by Django 5.0.14 on 2025-06-24 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0169_mttb_glmaster_mod_no_mttb_glmaster_outstanding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sttb_eoc_status',
            name='function_id',
        ),
        migrations.RemoveField(
            model_name='sttb_eoc_status',
            name='module_id',
        ),
    ]
