# Generated by Django 5.0.14 on 2025-06-23 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0170_fa_asset_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_accounting_method',
            name='asset_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_lists'),
        ),
        migrations.AlterField(
            model_name='fa_asset_expense',
            name='asset_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_lists'),
        ),
        migrations.AlterField(
            model_name='fa_asset_list_depreciation',
            name='asset_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_lists'),
        ),
        migrations.AlterField(
            model_name='fa_asset_list_disposal',
            name='asset_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_lists'),
        ),
        migrations.AlterField(
            model_name='fa_asset_photos',
            name='asset_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_lists'),
        ),
        migrations.AlterField(
            model_name='fa_depreciation_main',
            name='asset_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_lists'),
        ),
        migrations.AlterField(
            model_name='fa_maintenance_logs',
            name='asset_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_lists'),
        ),
        migrations.AlterField(
            model_name='fa_transfer_logs',
            name='asset_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_lists'),
        ),
    ]
