# Generated by Django 5.0.14 on 2025-06-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0171_alter_fa_accounting_method_asset_list_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FA_Asset_List',
        ),
    ]
