# Generated by Django 5.0.14 on 2025-06-23 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0172_delete_fa_asset_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_asset_lists',
            name='aaset_ac_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ac_asset_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
