# Generated by Django 5.0.14 on 2025-06-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0173_alter_fa_asset_lists_aaset_ac_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fa_asset_lists',
            old_name='aaset_ac_by',
            new_name='asset_ac_by',
        ),
    ]
