# Generated by Django 5.0.14 on 2025-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0174_rename_aaset_ac_by_fa_asset_lists_asset_ac_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_lists',
            name='asset_value_remainBegin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fa_asset_lists',
            name='asset_value_remainLast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fa_asset_lists',
            name='asset_value_remainMonth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
