# Generated by Django 5.0.14 on 2025-06-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0175_fa_asset_lists_asset_value_remainbegin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_lists',
            name='acc_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
