# Generated by Django 5.0.14 on 2025-06-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0176_fa_asset_lists_acc_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterType',
            fields=[
                ('M_id', models.AutoField(primary_key=True, serialize=False)),
                ('M_code', models.CharField(blank=True, max_length=50, null=True)),
                ('M_name_la', models.CharField(blank=True, max_length=255, null=True)),
                ('M_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('M_detail', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'MasterType',
            },
        ),
    ]
