# Generated by Django 5.0.14 on 2025-06-24 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0177_mastertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCode',
            fields=[
                ('MC_id', models.AutoField(primary_key=True, serialize=False)),
                ('MC_code', models.CharField(blank=True, max_length=50, null=True)),
                ('MC_name_la', models.CharField(blank=True, max_length=255, null=True)),
                ('MC_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('MC_detail', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
                ('BOL_code', models.CharField(blank=True, max_length=50, null=True)),
                ('BOL_name', models.CharField(blank=True, max_length=255, null=True)),
                ('M_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mastertype')),
            ],
            options={
                'verbose_name_plural': 'MasterCode',
            },
        ),
    ]
