# Generated by Django 5.0.14 on 2025-06-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0178_mastercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_lists',
            name='type_of_pay',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
