# Generated by Django 5.0.14 on 2025-06-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0170_remove_sttb_eoc_status_function_id_and_more'),
        ('SAMCSYS', '0179_fa_asset_lists_type_of_pay'),
    ]

    operations = [
    ]
