# Generated by Django 5.0.14 on 2025-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0180_merge_20250625_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detb_jrnl_log_hist',
            name='Reference_No',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detb_jrnl_log_master',
            name='Reference_No',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
