# Generated by Django 5.0.14 on 2025-06-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0181_alter_detb_jrnl_log_hist_reference_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detb_jrnl_log',
            name='Reference_sub_No',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='detb_jrnl_log_hist',
            name='Reference_sub_No',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
