# Generated by Django 5.0.14 on 2025-06-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0183_detb_jrnl_log_commments_detb_jrnl_log_hist_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detb_jrnl_log',
            old_name='commments',
            new_name='comments',
        ),
    ]
