# Generated by Django 5.0.14 on 2025-07-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0184_rename_commments_detb_jrnl_log_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_lists',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
    ]
