# Generated by Django 5.0.14 on 2025-07-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0184_rename_commments_detb_jrnl_log_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='actb_dairy_log',
            name='trn_ref_sub_no',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='actb_dairy_log_history',
            name='trn_ref_sub_no',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
