# Generated by Django 5.0.14 on 2025-07-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0185_actb_dairy_log_trn_ref_sub_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actb_dairy_log',
            name='glType',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
