# Generated by Django 5.0.14 on 2025-07-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0185_fa_asset_lists_auth_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_asset_lists',
            name='asset_status',
            field=models.CharField(blank=True, default='UC', max_length=20, null=True),
        ),
    ]
