# Generated by Django 5.0.14 on 2025-07-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0186_alter_fa_asset_lists_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_lists',
            name='accu_dpca_value_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
