# Generated by Django 5.0.14 on 2025-07-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0186_actb_dairy_log_gltype'),
        ('SAMCSYS', '0187_fa_asset_lists_accu_dpca_value_total'),
    ]

    operations = [
    ]
