# Generated by Django 5.0.14 on 2025-07-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0188_merge_20250707_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_lists',
            name='Auth_Status_ARC',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
    ]
