# Generated by Django 5.0.14 on 2025-07-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0189_fa_asset_lists_auth_status_arc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fa_accounting_method',
            name='journal_entry_id',
        ),
        migrations.AddField(
            model_name='fa_accounting_method',
            name='amount_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fa_accounting_method',
            name='amount_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
