# Generated by Django 5.0.14 on 2025-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0190_remove_fa_accounting_method_journal_entry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sttb_eoc_daily_log',
            name='addl_sub_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sttb_eoc_daily_log',
            name='trn_ref_sub_no',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
