# Generated by Django 5.0.14 on 2025-07-08 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0191_sttb_eoc_daily_log_addl_sub_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sttb_eoc_status',
            name='eoc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_eoc_maintain'),
        ),
    ]
