# Generated by Django 5.0.14 on 2025-07-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0191_sttb_eoc_daily_log_addl_sub_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_accounting_method',
            name='ref_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
