# Generated by Django 5.0.14 on 2025-07-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0192_alter_fa_accounting_method_ref_id'),
        ('SAMCSYS', '0192_sttb_eoc_status_eoc_id'),
    ]

    operations = [
    ]
