# Generated by Django 5.0.14 on 2025-07-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0193_merge_20250709_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sttb_dates',
            name='next_working_Day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
