# Generated by Django 5.0.14 on 2025-07-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0194_alter_sttb_dates_next_working_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sttb_dates',
            old_name='prev_Wroking_Day',
            new_name='prev_Working_Day',
        ),
    ]
