# Generated by Django 5.0.14 on 2025-07-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0193_alter_fa_accounting_method_ref_id'),
        ('SAMCSYS', '0195_rename_prev_wroking_day_sttb_dates_prev_working_day'),
    ]

    operations = [
    ]
