# Generated by Django 5.0.14 on 2025-07-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0196_merge_20250711_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mttb_employee',
            old_name='record_stat',
            new_name='Record_Status',
        ),
    ]
