# Generated by Django 5.0.14 on 2025-07-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0197_rename_record_stat_mttb_employee_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_lists',
            name='C_dpac',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
    ]
