# Generated by Django 5.0.14 on 2025-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0198_fa_asset_lists_c_dpac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_transfer_logs',
            name='approved_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fa_transfer_logs',
            name='received_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fa_transfer_logs',
            name='requested_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
