# Generated by Django 5.0.14 on 2025-07-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0199_alter_fa_transfer_logs_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fa_depreciation_main',
            name='Checker_Id',
        ),
        migrations.RemoveField(
            model_name='fa_depreciation_main',
            name='Maker_Id',
        ),
        migrations.RemoveField(
            model_name='fa_depreciation_main',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='fa_depreciation_sub',
            name='m_id',
        ),
        migrations.RemoveField(
            model_name='fa_depreciation_sub',
            name='Checker_Id',
        ),
        migrations.RemoveField(
            model_name='fa_depreciation_sub',
            name='Maker_Id',
        ),
        migrations.RemoveField(
            model_name='fa_depreciation_sub',
            name='approve_by',
        ),
        migrations.DeleteModel(
            name='FA_Asset_List_Depreciation',
        ),
        migrations.DeleteModel(
            name='FA_Depreciation_Main',
        ),
        migrations.DeleteModel(
            name='FA_Depreciation_Sub',
        ),
    ]
