# Generated by Django 5.0.14 on 2025-07-15 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0200_remove_fa_depreciation_main_checker_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Asset_List_Depreciation_Main',
            fields=[
                ('aldm_id', models.AutoField(primary_key=True, serialize=False)),
                ('dpca_year', models.CharField(blank=True, max_length=4, null=True)),
                ('dpca_month', models.CharField(blank=True, max_length=7, null=True)),
                ('dpca_date', models.DateField(blank=True, null=True)),
                ('dpca_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dpca_no_of_days', models.IntegerField(blank=True, null=True)),
                ('remaining_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('accumulated_dpca', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dpca_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('dpca_ac_yesno', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('dpca_ac_date', models.DateField(blank=True, null=True)),
                ('dpca_datetime', models.DateTimeField(blank=True, null=True)),
                ('dpca_ac_by', models.IntegerField(blank=True, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_list_depreciation_main', to=settings.AUTH_USER_MODEL)),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_list_depreciation_main', to=settings.AUTH_USER_MODEL)),
                ('asset_list_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_lists')),
            ],
            options={
                'verbose_name_plural': 'AssestListDepreciationMain',
            },
        ),
    ]
