# Generated by Django 5.0.14 on 2025-07-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0202_fa_asset_list_depreciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actb_dairy_log_history',
            name='trn_ref_no',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
