# Generated by Django 5.0.14 on 2025-07-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0203_alter_actb_dairy_log_history_trn_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sttb_eoc_daily_log',
            name='trn_ref_no',
            field=models.CharField(max_length=35),
        ),
    ]
