# Generated by Django 5.0.14 on 2025-07-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0204_alter_sttb_eoc_daily_log_trn_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sttb_eoc_daily_log',
            name='period_code',
            field=models.CharField(max_length=6),
        ),
    ]
