# Generated by Django 5.0.14 on 2025-07-22 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0205_alter_sttb_eoc_daily_log_period_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Asset_List_Depreciation_InMonth',
            fields=[
                ('aldim_id', models.AutoField(primary_key=True, serialize=False)),
                ('dpca_month', models.CharField(blank=True, max_length=7, null=True)),
                ('C_dpca', models.CharField(blank=True, default='0', max_length=5, null=True)),
                ('dpca_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dpca_status', models.CharField(blank=True, default='PENDING', max_length=20, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_asset_list_depreciation_inmain', to=settings.AUTH_USER_MODEL)),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_list_depreciation_inmain', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AssestListDepreciationInMain',
            },
        ),
    ]
