# Generated by Django 5.0.14 on 2025-07-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0206_fa_asset_list_depreciation_inmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_list_depreciation_inmonth',
            name='Record_Status',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
    ]
