# Generated by Django 5.0.14 on 2025-07-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0207_fa_asset_list_depreciation_inmonth_record_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('indID', models.AutoField(primary_key=True, serialize=False)),
                ('BankID', models.CharField(blank=True, max_length=30, null=True)),
                ('BankCustomerID', models.CharField(blank=True, max_length=50, null=True)),
                ('BranchIDCode', models.CharField(blank=True, max_length=30, null=True)),
                ('GroupID', models.CharField(blank=True, max_length=30, null=True)),
                ('HeadOfGroup', models.CharField(blank=True, max_length=10, null=True)),
                ('NationalID', models.CharField(blank=True, max_length=30, null=True)),
                ('NationalIDExpiryDate', models.DateTimeField(blank=True, null=True)),
                ('PassID', models.CharField(blank=True, max_length=30, null=True)),
                ('PassExpiryDate', models.DateTimeField(blank=True, null=True)),
                ('FBID', models.CharField(blank=True, max_length=30, null=True)),
                ('FBProvinceCodeOfIssue', models.CharField(blank=True, max_length=30, null=True)),
                ('FBIssueDate', models.DateTimeField(blank=True, null=True)),
                ('BirthDate', models.DateTimeField(blank=True, null=True)),
                ('FNameE', models.CharField(blank=True, max_length=80, null=True)),
                ('NickNameE', models.CharField(blank=True, max_length=30, null=True)),
                ('SurNameE', models.CharField(blank=True, max_length=80, null=True)),
                ('FNameL', models.CharField(blank=True, max_length=80, null=True)),
                ('SurNameL', models.CharField(blank=True, max_length=80, null=True)),
                ('OldSurNameE', models.CharField(blank=True, max_length=80, null=True)),
                ('OldSurNameL', models.CharField(blank=True, max_length=30, null=True)),
                ('Nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('Gender', models.CharField(blank=True, max_length=1, null=True)),
                ('CivilStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('SpouseFNameE', models.CharField(blank=True, max_length=80, null=True)),
                ('SpouseNickNameE', models.CharField(blank=True, max_length=80, null=True)),
                ('SpouseSurNameE', models.CharField(blank=True, max_length=80, null=True)),
                ('SpouseFNameL', models.CharField(blank=True, max_length=80, null=True)),
                ('SpouseSurnameL', models.CharField(blank=True, max_length=80, null=True)),
                ('Category', models.CharField(blank=True, max_length=5, null=True)),
                ('Status', models.CharField(blank=True, max_length=1, null=True)),
                ('UserID', models.IntegerField(blank=True, null=True)),
                ('DateInsert', models.DateTimeField(blank=True, null=True)),
                ('DateUpdate', models.DateTimeField(blank=True, null=True)),
                ('RelationShip', models.CharField(blank=True, max_length=50, null=True)),
                ('career', models.CharField(blank=True, max_length=50, null=True)),
                ('SumOfValues', models.FloatField(blank=True, null=True)),
                ('TaxNo', models.CharField(blank=True, max_length=50, null=True)),
                ('NationNo', models.CharField(blank=True, max_length=50, null=True)),
                ('NationalIssue', models.DateTimeField(blank=True, null=True)),
                ('PassIssue', models.DateTimeField(blank=True, null=True)),
                ('FBNameOfHead', models.CharField(blank=True, max_length=50, null=True)),
                ('BBankID', models.CharField(blank=True, max_length=50, null=True)),
                ('BAccountID', models.CharField(blank=True, max_length=50, null=True)),
                ('BAccountNameE', models.CharField(blank=True, max_length=550, null=True)),
                ('BAccountNameL', models.CharField(blank=True, max_length=550, null=True)),
                ('BCurrency', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Individual',
            },
        ),
    ]
