# Generated by Django 5.0.14 on 2025-07-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0210_a4_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Individual',
            new_name='A1_Individual',
        ),
        migrations.RenameModel(
            old_name='Company',
            new_name='A2_Company',
        ),
        migrations.AlterModelOptions(
            name='a1_individual',
            options={'verbose_name_plural': 'A1_Individual'},
        ),
        migrations.AlterModelOptions(
            name='a2_company',
            options={'verbose_name_plural': 'A2_Company'},
        ),
    ]
