# Generated by Django 5.0.14 on 2025-07-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0211_rename_individual_a1_individual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='A5_TelephoneNO',
            fields=[
                ('A5ID', models.IntegerField(primary_key=True, serialize=False)),
                ('BankID', models.CharField(blank=True, max_length=30, null=True)),
                ('BankCustomerID', models.CharField(blank=True, max_length=50, null=True)),
                ('BranchIDCode', models.CharField(blank=True, max_length=30, null=True)),
                ('TelephoneNo', models.CharField(blank=True, max_length=30, null=True)),
                ('MobileNo', models.CharField(blank=True, max_length=30, null=True)),
                ('FaxNo', models.CharField(blank=True, max_length=30, null=True)),
                ('DateInput', models.DateTimeField(blank=True, null=True)),
                ('DateUpdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'A5_TelephoneNO',
            },
        ),
        migrations.AlterModelOptions(
            name='a4_address',
            options={'verbose_name_plural': 'A4_Address'},
        ),
    ]
