# Generated by Django 5.0.14 on 2025-07-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0215_b1_monthlyarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('BankID', models.AutoField(primary_key=True, serialize=False)),
                ('BankCode', models.CharField(blank=True, max_length=3, null=True)),
                ('BankNameE', models.CharField(blank=True, max_length=250, null=True)),
                ('BankNameL', models.CharField(blank=True, max_length=250, null=True)),
                ('BInfo', models.CharField(blank=True, max_length=250, null=True)),
                ('BTel', models.CharField(blank=True, max_length=20, null=True)),
                ('UID', models.IntegerField(blank=True, null=True)),
                ('DInsert', models.DateTimeField(blank=True, null=True)),
                ('DUpdate', models.DateTimeField(blank=True, null=True)),
                ('BOL_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('BOL_ApprovedDate', models.DateTimeField(blank=True, null=True)),
                ('VillageID', models.CharField(blank=True, max_length=50, null=True)),
                ('HouseUnit', models.CharField(blank=True, max_length=50, null=True)),
                ('HouseNo', models.CharField(blank=True, max_length=50, null=True)),
                ('EnterpriseCode', models.CharField(blank=True, max_length=50, null=True)),
                ('BolLicenseNO', models.CharField(blank=True, max_length=50, null=True)),
                ('BranchesAmount', models.FloatField(blank=True, null=True)),
                ('UnitsAmount', models.FloatField(blank=True, null=True)),
                ('BMobile', models.CharField(blank=True, max_length=50, null=True)),
                ('BFax', models.CharField(blank=True, max_length=50, null=True)),
                ('BEmail', models.CharField(blank=True, max_length=50, null=True)),
                ('WhatsApp', models.CharField(blank=True, max_length=50, null=True)),
                ('Website', models.CharField(blank=True, max_length=50, null=True)),
                ('OtherContactInfo', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('BBankID', models.CharField(blank=True, max_length=50, null=True)),
                ('BAccountID', models.CharField(blank=True, max_length=50, null=True)),
                ('BAccountNameE', models.CharField(blank=True, max_length=550, null=True)),
                ('BAccountNameL', models.CharField(blank=True, max_length=550, null=True)),
                ('BCurrency', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'BankInfo',
            },
        ),
    ]
