# Generated by Django 5.0.14 on 2025-07-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0216_bankinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInfo',
            fields=[
                ('BranchID', models.AutoField(primary_key=True, serialize=False)),
                ('BankID', models.IntegerField(blank=True, null=True)),
                ('BranchCode', models.CharField(blank=True, max_length=50, null=True)),
                ('BranchNameE', models.CharField(blank=True, max_length=50, null=True)),
                ('BranchNameL', models.CharField(blank=True, max_length=50, null=True)),
                ('UID', models.IntegerField(blank=True, null=True)),
                ('DInsert', models.DateTimeField(blank=True, null=True)),
                ('DUpdate', models.DateTimeField(blank=True, null=True)),
                ('SegmentType', models.CharField(blank=True, max_length=50, null=True)),
                ('BolBranch_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('BolBranchApproveDate', models.DateTimeField(blank=True, null=True)),
                ('VillageID', models.CharField(blank=True, max_length=50, null=True)),
                ('HouseUnit', models.CharField(blank=True, max_length=50, null=True)),
                ('HouseNo', models.CharField(blank=True, max_length=50, null=True)),
                ('BolBranchLicenseNo', models.CharField(blank=True, max_length=25, null=True)),
                ('BMobile', models.CharField(blank=True, max_length=20, null=True)),
                ('Fax', models.CharField(blank=True, max_length=15, null=True)),
                ('Email', models.CharField(blank=True, max_length=250, null=True)),
                ('WhatsApp', models.CharField(blank=True, max_length=50, null=True)),
                ('Website', models.CharField(blank=True, max_length=250, null=True)),
                ('OtherContact', models.CharField(blank=True, max_length=250, null=True)),
                ('Latitude', models.CharField(blank=True, max_length=500, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=500, null=True)),
                ('BranchType', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'BranchInfo',
            },
        ),
    ]
