# Generated by Django 5.0.14 on 2025-07-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0217_branchinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A2_Company',
        ),
        migrations.DeleteModel(
            name='A4_address',
        ),
        migrations.DeleteModel(
            name='A5_TelephoneNO',
        ),
    ]
