# Generated by Django 5.0.14 on 2025-07-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0218_delete_a2_company_delete_a4_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='A2_Company',
            fields=[
                ('ComID', models.AutoField(primary_key=True, serialize=False)),
                ('BankID', models.CharField(blank=True, max_length=30, null=True)),
                ('BankCustomerID', models.CharField(blank=True, max_length=50, null=True)),
                ('BranchIDCode', models.CharField(blank=True, max_length=30, null=True)),
                ('EnterpriseCode', models.CharField(blank=True, max_length=30, null=True)),
                ('RegisDateOfIssue', models.DateTimeField(blank=True, null=True)),
                ('RegisPlaceIssue', models.CharField(blank=True, max_length=250, null=True)),
                ('ComNameE', models.CharField(blank=True, max_length=250, null=True)),
                ('ComNameL', models.CharField(blank=True, max_length=250, null=True)),
                ('TaxNo', models.CharField(blank=True, max_length=30, null=True)),
                ('Category', models.CharField(blank=True, max_length=30, null=True)),
                ('PSOGender', models.CharField(blank=True, max_length=30, null=True)),
                ('PSOFNameE', models.CharField(blank=True, max_length=250, null=True)),
                ('PSONickNameE', models.CharField(blank=True, max_length=30, null=True)),
                ('PSOSurNameE', models.CharField(blank=True, max_length=250, null=True)),
                ('PSOFNameL', models.CharField(blank=True, max_length=250, null=True)),
                ('PSOSurNameL', models.CharField(blank=True, max_length=250, null=True)),
                ('GMGender', models.CharField(blank=True, max_length=30, null=True)),
                ('GMFNameE', models.CharField(blank=True, max_length=80, null=True)),
                ('GMNickNameE', models.CharField(blank=True, max_length=30, null=True)),
                ('GMSurNameE', models.CharField(blank=True, max_length=80, null=True)),
                ('GMFNameL', models.CharField(blank=True, max_length=80, null=True)),
                ('GMSurNameL', models.CharField(blank=True, max_length=50, null=True)),
                ('RegulatoryCapital', models.FloatField(blank=True, null=True)),
                ('CurrencyCode', models.CharField(blank=True, max_length=30, null=True)),
                ('Status', models.CharField(blank=True, max_length=1, null=True)),
                ('UserID', models.IntegerField(blank=True, null=True)),
                ('DateInsert', models.DateTimeField(blank=True, null=True)),
                ('DateUpdate', models.DateTimeField(blank=True, null=True)),
                ('enterprise_size_id', models.CharField(blank=True, max_length=50, null=True)),
                ('registrant', models.CharField(blank=True, max_length=50, null=True)),
                ('village_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'A2_Company',
            },
        ),
    ]
