# Generated by Django 5.0.14 on 2025-07-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0220_a4_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='A5_TelephoneNO',
            fields=[
                ('A5ID', models.AutoField(primary_key=True, serialize=False)),
                ('BankID', models.CharField(blank=True, max_length=30, null=True)),
                ('BankCustomerID', models.CharField(blank=True, max_length=50, null=True)),
                ('BranchIDCode', models.CharField(blank=True, max_length=30, null=True)),
                ('TelephoneNo', models.CharField(blank=True, max_length=30, null=True)),
                ('MobileNo', models.CharField(blank=True, max_length=30, null=True)),
                ('FaxNo', models.CharField(blank=True, max_length=30, null=True)),
                ('DateInput', models.DateTimeField(blank=True, null=True)),
                ('DateUpdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'A5_TelephoneNO',
            },
        ),
    ]
