# Generated by Django 5.0.14 on 2025-07-24 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0222_dairy_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy_report',
            name='acc_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='DP_ID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='gl_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_glmaster'),
        ),
    ]
