# Generated by Django 5.0.14 on 2025-07-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0223_dairy_report_acc_no_alter_dairy_report_dp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sttb_eoc_daily_log',
            name='fcy_cr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='sttb_eoc_daily_log',
            name='fcy_dr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='sttb_eoc_daily_log',
            name='lcy_cr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='sttb_eoc_daily_log',
            name='lcy_dr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=22, null=True),
        ),
    ]
