# Generated by Django 5.0.14 on 2025-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0224_sttb_eoc_daily_log_fcy_cr_sttb_eoc_daily_log_fcy_dr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sttb_eoc_daily_log',
            name='gl_acc_relative',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
