# Generated by Django 5.0.14 on 2025-07-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0225_sttb_eoc_daily_log_gl_acc_relative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairy_report',
            name='acc_no',
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='gl_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
