# Generated by Django 5.0.14 on 2025-07-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0226_remove_dairy_report_acc_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actb_dairy_log',
            old_name='auth_id',
            new_name='Checker_id',
        ),
        migrations.RenameField(
            model_name='actb_dairy_log',
            old_name='user_id',
            new_name='Maker_id',
        ),
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='auth_id',
            new_name='Checker_id',
        ),
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='user_id',
            new_name='Maker_id',
        ),
        migrations.AddField(
            model_name='sttb_eoc_daily_log',
            name='ac_no_full',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actb_dairy_log_history',
            name='ac_no_full',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_eoc_daily_log',
            name='ac_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sttb_eoc_daily_log',
            name='external_ref_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
