# Generated by Django 5.0.14 on 2025-07-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0228_rename_auth_id_actb_dairy_log_history_checker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actb_dairy_log',
            name='trn_ref_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
