# Generated by Django 5.0.14 on 2025-07-26 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0229_alter_actb_dairy_log_trn_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_list_depreciation',
            name='aldm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list_depreciation_inmonth'),
        ),
        migrations.AddField(
            model_name='fa_asset_lists',
            name='delete_Stat',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
