# Generated by Django 5.0.14 on 2025-07-26 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0230_fa_asset_list_depreciation_aldm_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_list_depreciation_main',
            name='aldm_month_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_list_depreciation_inmonth'),
        ),
    ]
