# Generated by Django 5.0.14 on 2025-07-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0231_fa_asset_list_depreciation_main_aldm_month_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairy_report',
            name='C1_CR',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='C1_CR_lcy',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='C1_DR',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='C1_DR_lcy',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='DP_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='Mo_Cr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='Mo_Cr_lcy',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='Mo_DR',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='Mo_DR_lcy',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='OP_CR',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='OP_CR_lcy',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='OP_DR',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dairy_report',
            name='OP_DR_lcy',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
    ]
