# Generated by Django 5.0.14 on 2025-07-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0233_alter_dairy_report_c1_cr_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detb_jrnl_log_master',
            index=models.Index(fields=['Auth_Status'], name='idx_jrnl_auth_status'),
        ),
        migrations.AddIndex(
            model_name='detb_jrnl_log_master',
            index=models.Index(fields=['Maker_Id'], name='idx_jrnl_maker_id'),
        ),
        migrations.AddIndex(
            model_name='detb_jrnl_log_master',
            index=models.Index(fields=['Value_date'], name='idx_jrnl_value_date'),
        ),
        migrations.AddIndex(
            model_name='detb_jrnl_log_master',
            index=models.Index(fields=['Reference_No'], name='idx_jrnl_reference_no'),
        ),
        migrations.AddIndex(
            model_name='detb_jrnl_log_master',
            index=models.Index(fields=['delete_stat'], name='idx_jrnl_delete_stat'),
        ),
        migrations.AddIndex(
            model_name='detb_jrnl_log_master',
            index=models.Index(fields=['Auth_Status', 'Maker_Id', 'delete_stat'], name='idx_jrnl_composite'),
        ),
        migrations.AddIndex(
            model_name='detb_jrnl_log_master',
            index=models.Index(fields=['module_id', 'Ccy_cd'], name='idx_jrnl_module_ccy'),
        ),
    ]
