# Generated by Django 5.0.14 on 2025-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0234_fa_asset_list_depreciation_auth_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_list_depreciation_main',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='fa_asset_list_depreciation_main',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
