# Generated by Django 5.0.14 on 2025-08-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0234_detb_jrnl_log_master_idx_jrnl_auth_status_and_more'),
        ('SAMCSYS', '0235_fa_asset_list_depreciation_main_auth_status_and_more'),
    ]

    operations = [
    ]
