# Generated by Django 5.0.14 on 2025-08-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0236_merge_20250804_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_list_depreciation_main',
            name='dpca_month_dedc',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
