# Generated by Django 5.0.14 on 2025-08-05 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0237_fa_asset_list_depreciation_main_dpca_month_dedc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_la', models.CharField(max_length=255, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Business/Company registration number', max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=100, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-\\(\\)]+$', 'Enter a valid telephone number.')])),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('director_name', models.CharField(blank=True, max_length=255, null=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
    ]
