# Generated by Django 5.0.14 on 2025-08-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0238_companyprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow_Acc',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('report_number', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('Pvalue', models.TextField(blank=True, null=True)),
                ('Mvalue', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_subtotal', models.BooleanField(blank=True, default=False, null=True)),
                ('is_total', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Cashflow_Acc',
            },
        ),
    ]
