# Generated by Django 5.0.14 on 2025-08-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0240_annual_asset_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual_asset_audit',
            name='photos_attached',
            field=models.ImageField(blank=True, null=True, upload_to='audit_photos/'),
        ),
    ]
