# Generated by Django 5.0.14 on 2025-08-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0241_alter_annual_asset_audit_photos_attached'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annual_Asset_Audit',
        ),
    ]
