# Generated by Django 5.0.14 on 2025-08-09 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0242_delete_annual_asset_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA_Asset_Audit',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_year', models.CharField(blank=True, max_length=4, null=True)),
                ('audit_period', models.CharField(blank=True, max_length=20, null=True)),
                ('audit_date', models.DateField(blank=True, null=True)),
                ('auditor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_status', models.CharField(blank=True, max_length=20, null=True)),
                ('condition_status', models.CharField(blank=True, max_length=15, null=True)),
                ('location_verified', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('actual_location', models.CharField(blank=True, max_length=200, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accumulated_depreciation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remaining_useful_life', models.IntegerField(blank=True, null=True)),
                ('serial_number_verified', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('tag_number_verified', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('insurance_coverage', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('maintenance_required', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('replacement_recommended', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('disposal_recommended', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('audit_findings', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('photos_attached', models.ImageField(blank=True, null=True, upload_to='audit_photos/')),
                ('documents_verified', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('follow_up_required', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('audit_status', models.CharField(blank=True, max_length=20, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('approver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('Record_Status', models.CharField(blank=True, default='C', max_length=1, null=True)),
                ('Maker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_DT_Stamp', models.DateTimeField(blank=True, null=True)),
                ('Checker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_FA_asset_audit', to=settings.AUTH_USER_MODEL)),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_FA_asset_audit', to=settings.AUTH_USER_MODEL)),
                ('asset_list_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.fa_asset_lists')),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_divisions')),
            ],
            options={
                'verbose_name_plural': 'FA_Asset_Audit',
            },
        ),
    ]
