# Generated by Django 5.0.14 on 2025-08-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0243_fa_asset_audit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='Checker_id',
            new_name='Checker_id_id',
        ),
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='Maker_id',
            new_name='Maker_id_id',
        ),
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='ac_ccy',
            new_name='ac_ccy_id',
        ),
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='ac_no',
            new_name='ac_no_id',
        ),
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='gl_acc_relative',
            new_name='ac_relative',
        ),
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='type',
            new_name='delete_stat',
        ),
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='financial_cycle',
            new_name='financial_cycle_id',
        ),
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='module',
            new_name='module_id',
        ),
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='period_code',
            new_name='period_code_id',
        ),
        migrations.RenameField(
            model_name='sttb_eoc_daily_log',
            old_name='trn_code',
            new_name='trn_code_id',
        ),
        migrations.AddField(
            model_name='sttb_eoc_daily_log',
            name='glType',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='sttb_eoc_daily_log',
            name='glid_id',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
