# Generated by Django 5.0.14 on 2025-08-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0244_rename_checker_id_sttb_eoc_daily_log_checker_id_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sttb_eoc_daily_log',
            name='glid_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
