# Generated by Django 5.0.14 on 2025-08-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0245_alter_sttb_eoc_daily_log_glid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sttb_dates',
            name='Start_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_dates',
            name='prev_Working_Day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
