# Generated by Django 5.0.14 on 2025-08-11 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0246_alter_sttb_dates_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sttb_gl_sub_bal',
            name='gl_sub',
        ),
        migrations.AddField(
            model_name='sttb_gl_bal',
            name='InsertDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sttb_gl_bal',
            name='MSegment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sttb_gl_bal',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_gl_bal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sttb_gl_bal',
            name='UpdateDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sttb_gl_sub_bal',
            name='InsertDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sttb_gl_sub_bal',
            name='MSegment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sttb_gl_sub_bal',
            name='Maker_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_gl_sub_bal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sttb_gl_sub_bal',
            name='UpdateDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sttb_gl_sub_bal',
            name='category',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='sttb_gl_sub_bal',
            name='gl_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_gl_bal',
            name='CCy_Code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_gl_bal',
            name='fin_year',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_gl_bal',
            name='gl_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_gl_bal',
            name='period_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_gl_sub_bal',
            name='CCy_Code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_gl_sub_bal',
            name='fin_year',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_gl_sub_bal',
            name='period_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
