# Generated by Django 5.0.14 on 2025-08-11 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0247_remove_sttb_gl_sub_bal_gl_sub_sttb_gl_bal_insertdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='STTB_Somtop_Trial_Balancesheet',
            fields=[
                ('somtop_trail_bal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gl_code', models.CharField(blank=True, max_length=100, null=True)),
                ('Desc', models.CharField(blank=True, max_length=255, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('OP_DR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('OP_CR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_DR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_Cr', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('C1_DR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('C1_CR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('OP_DR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('OP_CR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_DR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_Cr_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('C1_DR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('C1_CR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('InsertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True)),
                ('MSegment', models.CharField(blank=True, max_length=50, null=True)),
                ('CCy_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_ccy_defn')),
                ('Fin_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_fin_cycle')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_somtop_report', to=settings.AUTH_USER_MODEL)),
                ('Period_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_per_code')),
            ],
        ),
        migrations.CreateModel(
            name='STTB_Trial_Balancesheet',
            fields=[
                ('trial_bal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gl_code', models.CharField(blank=True, max_length=100, null=True)),
                ('Desc', models.CharField(blank=True, max_length=255, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('OP_DR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('OP_CR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_DR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_Cr', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('C1_DR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('C1_CR', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('OP_DR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('OP_CR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_DR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('Mo_Cr_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('C1_DR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('C1_CR_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('InsertDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True)),
                ('MSegment', models.CharField(blank=True, max_length=50, null=True)),
                ('CCy_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_ccy_defn')),
                ('Fin_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_fin_cycle')),
                ('Maker_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trail_report', to=settings.AUTH_USER_MODEL)),
                ('Period_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_per_code')),
            ],
        ),
    ]
