# Generated by Django 5.0.14 on 2025-08-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0248_sttb_somtop_trial_balancesheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sttb_gl_sub_bal',
            name='Maker_Id',
        ),
        migrations.DeleteModel(
            name='STTB_GL_BAL',
        ),
        migrations.DeleteModel(
            name='STTB_GL_SUB_BAL',
        ),
    ]
