# Generated by Django 5.0.14 on 2025-08-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0249_remove_sttb_gl_sub_bal_maker_id_delete_sttb_gl_bal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sttb_trial_balancesheet',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sttb_trial_balancesheet',
            name='StartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
