# Generated by Django 5.0.14 on 2025-08-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0250_sttb_trial_balancesheet_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sttb_somtop_trial_balancesheet',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sttb_somtop_trial_balancesheet',
            name='StartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
