# Generated by Django 5.0.14 on 2025-08-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0251_sttb_somtop_trial_balancesheet_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Balancesheet_acc',
            fields=[
                ('mb_acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(blank=True, max_length=20, null=True)),
                ('report_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('total_Amount_Opening', models.CharField(blank=True, max_length=50, null=True)),
                ('total_Amount_Current', models.CharField(blank=True, max_length=50, null=True)),
                ('total_net_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_display', models.CharField(blank=True, max_length=10, null=True)),
                ('segment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('period_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Monthly_Balancesheet_acc',
            },
        ),
    ]
