# Generated by Django 5.0.14 on 2025-08-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0254_monthly_incomestatement_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Incomestatement_mfi',
            fields=[
                ('mi_mfi_id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(blank=True, max_length=20, null=True)),
                ('report_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('previous_month', models.CharField(blank=True, max_length=50, null=True)),
                ('current_month', models.CharField(blank=True, max_length=50, null=True)),
                ('net_change', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_display', models.CharField(blank=True, max_length=10, null=True)),
                ('segment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('period_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Monthly_Incomestatement_mfi',
            },
        ),
    ]
