# Generated by Django 5.0.14 on 2025-08-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0255_monthly_incomestatement_mfi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STTB_Somtop_Trial_Balancesheet',
        ),
    ]
