# Generated by Django 5.0.14 on 2025-08-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0257_sttb_somtop_trial_balancesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mttb_users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/'),
        ),
    ]
