# Generated by Django 5.0.14 on 2025-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0258_alter_mttb_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_balancesheet_acc',
            name='currency_display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='monthly_balancesheet_acc',
            index=models.Index(fields=['period_code'], name='SAMCSYS_mon_period__ab1470_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_balancesheet_acc',
            index=models.Index(fields=['segment_type'], name='SAMCSYS_mon_segment_fdc79a_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_balancesheet_acc',
            index=models.Index(fields=['currency_display'], name='SAMCSYS_mon_currenc_6ae12b_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_balancesheet_acc',
            index=models.Index(fields=['period_code', 'segment_type'], name='SAMCSYS_mon_period__02075b_idx'),
        ),
        migrations.AlterModelTable(
            name='monthly_balancesheet_acc',
            table='SAMCSYS_monthly_balancesheet_acc',
        ),
    ]
