# Generated by Django 5.0.14 on 2025-08-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0259_alter_monthly_balancesheet_acc_currency_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_balancesheet_mfi',
            name='currency_display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='monthly_balancesheet_mfi',
            index=models.Index(fields=['period_code'], name='SAMCSYS_mon_period__bf6d45_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_balancesheet_mfi',
            index=models.Index(fields=['segment_type'], name='SAMCSYS_mon_segment_cdcd5a_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_balancesheet_mfi',
            index=models.Index(fields=['currency_display'], name='SAMCSYS_mon_currenc_1f45ad_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_balancesheet_mfi',
            index=models.Index(fields=['period_code', 'segment_type'], name='SAMCSYS_mon_period__a9cd1a_idx'),
        ),
        migrations.AlterModelTable(
            name='monthly_balancesheet_mfi',
            table='SAMCSYS_monthly_balancesheet_mfi',
        ),
    ]
