# Generated by Django 5.0.14 on 2025-08-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0260_alter_monthly_balancesheet_mfi_currency_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_incomestatement_acc',
            name='currency_display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_incomestatement_mfi',
            name='currency_display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='monthly_incomestatement_acc',
            index=models.Index(fields=['period_code'], name='SAMCSYS_mon_period__e7d1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_incomestatement_acc',
            index=models.Index(fields=['segment_type'], name='SAMCSYS_mon_segment_a58897_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_incomestatement_acc',
            index=models.Index(fields=['currency_display'], name='SAMCSYS_mon_currenc_8c6402_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_incomestatement_acc',
            index=models.Index(fields=['period_code', 'segment_type'], name='SAMCSYS_mon_period__a71f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_incomestatement_mfi',
            index=models.Index(fields=['period_code'], name='SAMCSYS_mon_period__897f08_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_incomestatement_mfi',
            index=models.Index(fields=['segment_type'], name='SAMCSYS_mon_segment_7caf03_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_incomestatement_mfi',
            index=models.Index(fields=['currency_display'], name='SAMCSYS_mon_currenc_ee0b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='monthly_incomestatement_mfi',
            index=models.Index(fields=['period_code', 'segment_type'], name='SAMCSYS_mon_period__d851b3_idx'),
        ),
        migrations.AlterModelTable(
            name='monthly_incomestatement_acc',
            table='SAMCSYS_monthly_incomestatement_acc',
        ),
        migrations.AlterModelTable(
            name='monthly_incomestatement_mfi',
            table='SAMCSYS_monthly_incomestatement_mfi',
        ),
    ]
