# Generated by Django 5.0.14 on 2025-08-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0261_alter_monthly_incomestatement_acc_currency_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow_acc',
            name='Extensions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cashflow_acc',
            name='Reductions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
