# Generated by Django 5.0.14 on 2025-08-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0262_cashflow_acc_extensions_cashflow_acc_reductions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Cashflow',
            fields=[
                ('RID', models.AutoField(primary_key=True, serialize=False)),
                ('Report_number', models.CharField(blank=True, max_length=10, null=True)),
                ('org_formula', models.TextField(blank=True, null=True)),
                ('Pvalue', models.TextField(blank=True, null=True)),
                ('Mvalue', models.TextField(blank=True, null=True)),
                ('TypeOfReport', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Report_Cashflow',
            },
        ),
    ]
