# Generated by Django 5.0.14 on 2025-08-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0263_report_cashflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_cashflow',
            name='Report_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
