# Generated by Django 5.0.14 on 2025-08-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0264_alter_report_cashflow_report_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_cashflow',
            name='COE_order',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report_cashflow',
            name='CR_order',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report_cashflow',
            name='Extensions',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report_cashflow',
            name='Reductions',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
