# Generated by Django 5.0.14 on 2025-08-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0264_alter_report_cashflow_report_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fa_asset_lists',
            table='fa_asset_lists',
        ),
    ]
