# Generated by Django 5.0.14 on 2025-08-25 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0265_alter_fa_asset_lists_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fa_asset_lists',
            name='delete_Stat',
        ),
    ]
