# Generated by Django 5.0.14 on 2025-08-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0265_report_cashflow_coe_order_report_cashflow_cr_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_cashflow',
            name='Mvalue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report_cashflow',
            name='Pvalue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
