# Generated by Django 5.0.14 on 2025-08-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0266_alter_report_cashflow_mvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_cashflow',
            name='REP_Desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='report_cashflow',
            name='org_formula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
