# Generated by Django 5.0.14 on 2025-08-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0266_remove_fa_asset_lists_delete_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_lists',
            name='delete_Stat',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
