# Generated by Django 5.0.14 on 2025-08-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0267_fa_asset_lists_delete_stat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fa_asset_lists',
            table=None,
        ),
    ]
