# Generated by Django 5.0.14 on 2025-08-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0268_alter_report_cashflow_mvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_cashflow',
            name='Mvalue',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='report_cashflow',
            name='Pvalue',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='report_cashflow',
            name='org_formula',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
