# Generated by Django 5.0.14 on 2025-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0269_alter_report_cashflow_mvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_cashflow',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
