# Generated by Django 5.0.14 on 2025-08-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0268_alter_fa_asset_lists_table'),
        ('SAMCSYS', '0270_report_cashflow_category'),
    ]

    operations = [
    ]
