# Generated by Django 5.0.14 on 2025-08-27 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0271_merge_20250825_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_lists',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAMCSYS.mttb_divisions'),
        ),
    ]
