# Generated by Django 5.0.14 on 2025-08-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0272_fa_asset_lists_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_asset_list_disposal',
            name='disposal_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
