# Generated by Django 5.0.14 on 2025-08-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0273_alter_fa_asset_list_disposal_disposal_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_asset_list_disposal',
            name='gain_loss',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
