# Generated by Django 5.0.14 on 2025-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0274_alter_fa_asset_list_disposal_gain_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow_acc',
            name='CF_command',
            field=models.TextField(blank=True, null=True),
        ),
    ]
