# Generated by Django 5.0.14 on 2025-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0275_cashflow_acc_cf_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Cashflow_acc',
            fields=[
                ('mi_acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(blank=True, max_length=20, null=True)),
                ('report_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('previous_month', models.CharField(blank=True, max_length=50, null=True)),
                ('current_month', models.CharField(blank=True, max_length=50, null=True)),
                ('net_change', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_display', models.CharField(blank=True, max_length=50, null=True)),
                ('segment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('period_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_Cashflow_mfi',
            fields=[
                ('mi_mfi_id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(blank=True, max_length=20, null=True)),
                ('report_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('previous_month', models.CharField(blank=True, max_length=50, null=True)),
                ('current_month', models.CharField(blank=True, max_length=50, null=True)),
                ('net_change', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_display', models.CharField(blank=True, max_length=50, null=True)),
                ('segment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('period_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
