# Generated by Django 5.0.14 on 2025-09-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0276_monthly_cashflow_acc_monthly_cashflow_mfi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mttb_exc_rate',
            name='value_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mttb_exc_rate_history',
            name='value_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
