# Generated by Django 5.0.14 on 2025-09-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0276_monthly_cashflow_acc_monthly_cashflow_mfi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_asset_lists',
            name='accu_dpca_value_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fa_asset_lists',
            name='asset_accu_dpca_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fa_asset_lists',
            name='asset_value_remain',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fa_asset_lists',
            name='asset_value_remainBegin',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fa_asset_lists',
            name='asset_value_remainLast',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fa_asset_lists',
            name='asset_value_remainMonth',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
