# Generated by Django 5.0.14 on 2025-09-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0277_mttb_exc_rate_value_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_list_disposal',
            name='Auth_Status',
            field=models.CharField(blank=True, default='U', max_length=1, null=True),
        ),
    ]
