# Generated by Django 5.0.14 on 2025-09-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0277_alter_fa_asset_lists_accu_dpca_value_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_accounting_method',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fa_accounting_method',
            name='amount_end',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fa_accounting_method',
            name='amount_start',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
