# Generated by Django 5.0.14 on 2025-09-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0278_fa_asset_list_disposal_auth_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow_acc',
            name='Mvalue_new',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflow_acc',
            name='Pvalue_new',
            field=models.TextField(blank=True, null=True),
        ),
    ]
