# Generated by Django 5.0.14 on 2025-09-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0278_alter_fa_accounting_method_amount_and_more'),
        ('SAMCSYS', '0278_fa_asset_list_disposal_auth_status'),
    ]

    operations = [
    ]
