# Generated by Django 5.0.14 on 2025-09-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0279_cashflow_acc_mvalue_new_cashflow_acc_pvalue_new'),
        ('SAMCSYS', '0279_merge_20250918_1023'),
    ]

    operations = [
    ]
