# Generated by Django 5.0.14 on 2025-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0280_merge_20250924_1025'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detb_jrnl_log',
            name='unique_journal_entry',
        ),
        migrations.AlterUniqueTogether(
            name='detb_jrnl_log',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='detb_jrnl_log',
            index=models.Index(fields=['Reference_No'], name='idx_jrnl_ref_no'),
        ),
        migrations.AddIndex(
            model_name='detb_jrnl_log',
            index=models.Index(fields=['Account', 'Value_date'], name='idx_jrnl_acct_date'),
        ),
        migrations.AddIndex(
            model_name='detb_jrnl_log',
            index=models.Index(fields=['Auth_Status'], name='idx_jrnl_auth'),
        ),
    ]
