# Generated by Django 4.2.20 on 2025-09-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0280_merge_20250924_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actb_dairy_log',
            name='value_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actb_dairy_log_history',
            name='value_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sttb_eoc_daily_log',
            name='value_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
