# Generated by Django 5.0.14 on 2025-09-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0281_remove_detb_jrnl_log_unique_journal_entry_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS SAMCSYS_detb_jrnl_log_Reference_No_Account_id_Dr_cr_Fcy_Amount_20d10b52_uniq ON SAMCSYS_detb_jrnl_log",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
