# Generated by Django 5.0.14 on 2025-10-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0281_alter_actb_dairy_log_value_dt_and_more'),
        ('SAMCSYS', '0282_remove_journal_unique_constraint'),
    ]

    operations = [
    ]
