# Generated by Django 5.0.14 on 2025-10-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0283_merge_20251001_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='sttb_somtop_trial_balancesheet',
            name='Eoc_status',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
