# Generated by Django 5.0.14 on 2025-10-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0284_sttb_somtop_trial_balancesheet_eoc_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETB_JRNL_SEQUENCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_key', models.CharField(db_index=True, help_text='Format: MODULE-TXN-YYYYMMDD', max_length=50, unique=True)),
                ('current_sequence', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DETB_JRNL_SEQUENCE',
                'indexes': [models.Index(fields=['sequence_key'], name='DETB_JRNL_S_sequenc_a872c3_idx'), models.Index(fields=['last_updated'], name='DETB_JRNL_S_last_up_225bf4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='detb_jrnl_sequence',
            constraint=models.CheckConstraint(check=models.Q(('current_sequence__gte', 0)), name='sequence_non_negative'),
        ),
    ]
