# Generated by Django 5.0.14 on 2025-10-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0285_detb_jrnl_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_maintenance_logs',
            name='quarter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
