# Generated by Django 5.0.14 on 2025-10-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAMCSYS', '0286_fa_maintenance_logs_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fa_asset_audit',
            name='quarter',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
